{
    "apps": [
        {
            "arch": "arm", 
            "build_date": "2025-09-05_09:21:10", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frps.asp", 
            "md5": "fe2bd3722acbb1f2786a4af45b23e7fe", 
            "name": "frps", 
            "tar_url": "frps/frps.tar.gz", 
            "title": "frps穿透服务器", 
            "version": "2.2"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:20", 
            "description": "简便高效的异地组网、内网穿透工具", 
            "home_url": "Module_vnt.asp", 
            "md5": "4328da7192f14534b817dd56fc834dc4", 
            "name": "vnt", 
            "tar_url": "vnt/vnt.tar.gz", 
            "title": "vnt", 
            "version": "1.2"
        }, 
        {
            "arch": "arm", 
            "build_date": "2025-03-08_15:54:13", 
            "description": "tailscale", 
            "home_url": "Module_tailscale.asp", 
            "md5": "2f645825c9c61c354f511643f9a424b3", 
            "name": "tailscale", 
            "tar_url": "tailscale/tailscale.tar.gz", 
            "title": "tailscale", 
            "version": "0.0.9"
        }, 
        {
            "arch": "arm", 
            "build_date": "2025-09-04_22:50:38", 
            "description": "Socat 端口转发", 
            "home_url": "Module_socat.asp", 
            "md5": "61eef81721cdc70ef2fbd3044fb4b2c8", 
            "name": "socat", 
            "tar_url": "socat/socat.tar.gz", 
            "title": "Socat端口转发", 
            "version": "1.2"
        }, 
        {
            "arch": "arm", 
            "build_date": "2025-09-04_22:17:23", 
            "description": "VPN全家桶, ver 4.44 build 9807", 
            "home_url": "", 
            "md5": "68716db316eb877e8ec107a9986b098f", 
            "name": "softether", 
            "tar_url": "softether/softether.tar.gz", 
            "title": "SoftEther_VPN_Server", 
            "version": "2.5"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:31", 
            "description": "局域网网速测试工具", 
            "home_url": "Module_speedtest.asp", 
            "md5": "baf829737f22066e7896fb6868c88011", 
            "name": "speedtest", 
            "tar_url": "speedtest/speedtest.tar.gz", 
            "title": "局域网测速", 
            "version": "0.0.4"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:33", 
            "description": "FileBrowser：您的可视化路由文件管理系统", 
            "home_url": "Module_filebrowser.asp", 
            "md5": "c270ee089537fda5659390f84d1d1fa5", 
            "name": "filebrowser", 
            "tar_url": "filebrowser/filebrowser.tar.gz", 
            "title": "filebrowser", 
            "version": "1.0.7"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:34", 
            "description": "去广告，没烦恼", 
            "home_url": "Module_koolproxy.asp", 
            "md5": "2b2e335a58fa712b411f2044eb5d1984", 
            "name": "koolproxy", 
            "tar_url": "koolproxy/koolproxy.tar.gz", 
            "title": "koolproxy", 
            "version": "3.8.5.6"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:35", 
            "description": "阿里云盘 WebDAV 服务器", 
            "home_url": "Module_aliyundrivewebdav.asp", 
            "md5": "b6144864688df8b763319d98147cf65d", 
            "name": "aliyundrivewebdav", 
            "tar_url": "aliyundrivewebdav/aliyundrivewebdav.tar.gz", 
            "title": "阿里云盘WebDAV", 
            "version": "1.8.2"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:36", 
            "description": "老板，来一斤虚拟内存~", 
            "home_url": "Module_swap.asp", 
            "md5": "028836b8f544e80fe361ecb4a5d3e4f1", 
            "name": "swap", 
            "tar_url": "swap/swap.tar.gz", 
            "title": "虚拟内存", 
            "version": "2.6"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:36", 
            "description": "花生壳内网穿透", 
            "home_url": "Module_phddns.asp", 
            "md5": "95309d09d45600c553cfc9dbf18b11c4", 
            "name": "phddns", 
            "tar_url": "phddns/phddns.tar.gz", 
            "title": "花生壳内网穿透", 
            "version": "3.0.6"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:37", 
            "description": "分布式的虚拟以太网", 
            "home_url": "Module_zerotier.asp", 
            "md5": "e6809476501b694f1d296bf820a71342", 
            "name": "zerotier", 
            "tar_url": "zerotier/zerotier.tar.gz", 
            "title": "zerotier", 
            "version": "1.6"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:38", 
            "description": "解锁网易云灰色歌曲", 
            "home_url": "Module_unblockmusic.asp", 
            "md5": "99bc8b91bb41cac4ffb0752f78a817f4", 
            "name": "unblockmusic", 
            "tar_url": "unblockmusic/unblockmusic.tar.gz", 
            "title": "解锁网易云灰色歌曲", 
            "version": "1.2.1"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:38", 
            "description": "Cloudflare解析自动更新IP", 
            "home_url": "Module_cfddns.asp", 
            "md5": "8fd2f0f3d2aea305975f03b763f8dc2f", 
            "name": "cfddns", 
            "tar_url": "cfddns/cfddns.tar.gz", 
            "title": "Cloudflare DDNS", 
            "version": "1.9"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:39", 
            "description": "灵缇游戏加速插件", 
            "home_url": "Module_lingti.asp", 
            "md5": "8d367a241587e1c45b03c6b51fca89e8", 
            "name": "lingti", 
            "tar_url": "lingti/lingti.tar.gz", 
            "title": "灵缇游戏加速插件", 
            "version": "1.0.3"
        }, 
        {
            "arch": "arm", 
            "build_date": "2025-03-23_14:29:51", 
            "description": "lucky", 
            "home_url": "Module_lucky.asp", 
            "md5": "f072f93ae90d2f49e9b45561c7d7fea5", 
            "name": "lucky", 
            "tar_url": "lucky/lucky.tar.gz", 
            "title": "lucky", 
            "version": "1.4.3"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:39", 
            "description": "kms", 
            "home_url": "Module_kms.asp", 
            "md5": "ef6ecc6e25f0eb829fa12618db05cb2d", 
            "name": "kms", 
            "tar_url": "kms/kms.tar.gz", 
            "title": "系统工具", 
            "version": "2.0"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:40", 
            "description": "解决重启Bug", 
            "home_url": "Module_reboothelper.asp", 
            "md5": "cdae23d4bbdc98f9e2043e2f2416b147", 
            "name": "reboothelper", 
            "tar_url": "reboothelper/reboothelper.tar.gz", 
            "title": "重启助手", 
            "version": "0.5"
        }, 
        {
            "arch": "arm", 
            "build_date": "2025-09-04_08:16:20", 
            "description": "支持Alidns(阿里云) Dnspod(腾讯云) Cloudflare 华为云 Callback", 
            "home_url": "Module_ddns.asp", 
            "md5": "2d1c67102013f75d6dd3c3826dfa336c", 
            "name": "ddns", 
            "tar_url": "ddns/ddns.tar.gz", 
            "title": "多ddns合一", 
            "version": "0.4"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:40", 
            "description": "自己的私有云", 
            "home_url": "Module_verysync.asp", 
            "md5": "555ebc628fe8742d94101ebb5fe47aa4", 
            "name": "verysync", 
            "tar_url": "verysync/verysync.tar.gz", 
            "title": "微力同步", 
            "version": "1.1.1"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:41", 
            "description": "自动部署SSL证书", 
            "home_url": "Module_acme.asp", 
            "md5": "ac4b24c0238588e8ca9af6ac866ca6e0", 
            "name": "acme", 
            "tar_url": "acme/acme.tar.gz", 
            "title": "Let's Encrypt", 
            "version": "3.5"
        }, 
        {
            "arch": "arm", 
            "build_date": "2025-09-05_14:30:20", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frpc.asp", 
            "md5": "f3d31256adaced10be0181eb290791a9", 
            "name": "frpc", 
            "tar_url": "frpc/frpc.tar.gz", 
            "title": "frpc穿透", 
            "version": "2.6"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:42", 
            "description": "aliddns", 
            "home_url": "Module_aliddns.asp", 
            "md5": "7530375ddf5e3866dd70a175e6264571", 
            "name": "aliddns", 
            "tar_url": "aliddns/aliddns.tar.gz", 
            "title": "阿里DDNS", 
            "version": "2.6"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:42", 
            "description": "广告屏蔽大师 Plus 可以全面过滤各种横幅、弹窗、视频广告，同时阻止跟踪、隐私窃取及各种恶意网站", 
            "home_url": "Module_adbyby.asp", 
            "md5": "2501652ce2596983a5512ce334c0c739", 
            "name": "adbyby", 
            "tar_url": "adbyby/adbyby.tar.gz", 
            "title": "广告屏蔽大师 Plus", 
            "version": "1.4"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:43", 
            "description": "pppoe单线多拨，带宽提升神器！", 
            "home_url": "Module_mdial.asp", 
            "md5": "c482030938c0cdbd32a9f05de694966a", 
            "name": "mdial", 
            "tar_url": "mdial/mdial.tar.gz", 
            "title": "单线多拨", 
            "version": "1.7"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:43", 
            "description": "linux下载利器", 
            "home_url": "Module_aria2.asp", 
            "md5": "a7b7fc2b5be338e087c8bd837c91c82e", 
            "name": "aria2", 
            "tar_url": "aria2/aria2.tar.gz", 
            "title": "Aria2", 
            "version": "3.2"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-12-04_18:20:20", 
            "description": "Cloudflare Tunnel 客户端(以前称为 Argo Tunnel)", 
            "home_url": "Module_cloudflared.asp", 
            "md5": "370be58f82ea71397157e35d3f6c11d2", 
            "name": "cloudflared", 
            "tar_url": "cloudflared/cloudflared.tar.gz", 
            "title": "cloudflared", 
            "version": "1.2"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:45", 
            "description": "这是一只自动帮你签到的dog", 
            "home_url": "Module_qiandao.asp", 
            "md5": "a91549fc7efc8f901c0b5e6206f61123", 
            "name": "qiandao", 
            "tar_url": "qiandao/qiandao.tar.gz", 
            "title": "签到dog", 
            "version": "1.8"
        }, 
        {
            "arch": "arm", 
            "build_date": "2025-09-04_12:06:46", 
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav。", 
            "home_url": "Module_openlist.asp", 
            "md5": "155f19aa984f86bb3d4920fced9d3f69", 
            "name": "openlist", 
            "tar_url": "openlist/openlist.tar.gz", 
            "title": "OpenList文件列表", 
            "version": "1.0"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:47", 
            "description": "光猫助手: 快速设置，通过路由直接访问猫后台", 
            "home_url": "Module_lookcat.asp", 
            "md5": "fd5f2e6691d6eac0679b1f4b002ca97f", 
            "name": "lookcat", 
            "tar_url": "lookcat/lookcat.tar.gz", 
            "title": "光猫助手", 
            "version": "1.2"
        }, 
        {
            "arch": "arm", 
            "build_date": "2025-09-04_22:51:58", 
            "description": "超强的SSH网页客户端~", 
            "home_url": "Module_shellinabox.asp", 
            "md5": "257fc8b5d489d82d9377f755845c2a15", 
            "name": "shellinabox", 
            "tar_url": "shellinabox/shellinabox.tar.gz", 
            "title": "shellinabox", 
            "version": "2.5"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:47", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_serverchan.asp", 
            "md5": "45300d6db76a5c1dac2901d2847e2673", 
            "name": "serverchan", 
            "tar_url": "serverchan/serverchan.tar.gz", 
            "title": "ServerChan微信推送", 
            "version": "2.7"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:48", 
            "description": "使用Dnspod的ddns服务", 
            "home_url": "Module_ddnspod.asp", 
            "md5": "f710bf5075d35f4b5970e6f65b18dc1d", 
            "name": "ddnspod", 
            "tar_url": "ddnspod/ddnspod.tar.gz", 
            "title": "DDnspod", 
            "version": "2.0"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:49", 
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav，后端基于gin，前端使用react。", 
            "home_url": "Module_alist.asp", 
            "md5": "747508384c7681e13b9134db393a23f8", 
            "name": "alist", 
            "tar_url": "alist/alist.tar.gz", 
            "title": "Alist文件列表", 
            "version": "1.9.2"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:55", 
            "description": "百度盘", 
            "home_url": "Module_baidupcs.asp", 
            "md5": "44c756e08311f12d461348f8a5705ad1", 
            "name": "baidupcs", 
            "tar_url": "baidupcs/baidupcs.tar.gz", 
            "title": "百度盘", 
            "version": "1.9"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:58", 
            "description": "DDNSTO远程控制", 
            "home_url": "Module_ddnsto.asp", 
            "md5": "ac8d2e7009a5ecfce071cd9b74bc011e", 
            "name": "ddnsto", 
            "tar_url": "ddnsto/ddnsto.tar.gz", 
            "title": "DDNSTO远程控制", 
            "version": "3.0.3"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-11-09_12:35:59", 
            "description": "腾讯云ddns", 
            "home_url": "Module_tenddns.asp", 
            "md5": "f4f73c88f48bb8e1d56d303c19113a35", 
            "name": "tenddns", 
            "tar_url": "tenddns/tenddns.tar.gz", 
            "title": "腾讯云ddns", 
            "version": "0.0.4"
        }
    ], 
    "home_url": "https://raw.githubusercontent.com/SWRT-dev/softcenter/master", 
    "md5": "96809bfabc423392145c7878507333a5", 
    "tar_url": "softcenter/softcenter.tar.gz", 
    "version": "1.5.6"
}