{
    "apps": [
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:11:48", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frps.asp", 
            "md5": "0d96c0c0abb1c3cd9081595c43261eda", 
            "name": "frps", 
            "tar_url": "arm/frps/frps.tar.gz", 
            "title": "frps穿透服务器", 
            "version": "2.1"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:11:49", 
            "description": "简便高效的异地组网、内网穿透工具", 
            "home_url": "Module_vnt.asp", 
            "md5": "aa8c5f7e1cbad32056bc6394d260420b", 
            "name": "vnt", 
            "tar_url": "arm/vnt/vnt.tar.gz", 
            "title": "vnt", 
            "version": "1.2"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:11:51", 
            "description": "tailscale", 
            "home_url": "Module_tailscale.asp", 
            "md5": "6e898e137adaf07e620e1068d733ff84", 
            "name": "tailscale", 
            "tar_url": "arm/tailscale/tailscale.tar.gz", 
            "title": "tailscale", 
            "version": "0.0.8"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:11:55", 
            "description": "Socat 端口转发", 
            "home_url": "Module_socat.asp", 
            "md5": "c867899d1e86482f3c8682dbffa56fa1", 
            "name": "socat", 
            "tar_url": "arm/socat/socat.tar.gz", 
            "title": "Socat端口转发", 
            "version": "1.1"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:11:55", 
            "description": "VPN全家桶, ver 4.30 build 9700", 
            "home_url": "", 
            "md5": "52a4f1b633043f24f46c4ca47822b2c5", 
            "name": "softether", 
            "tar_url": "arm/softether/softether.tar.gz", 
            "title": "SoftEther_VPN_Server", 
            "version": "2.4"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:11:57", 
            "description": "局域网网速测试工具", 
            "home_url": "Module_speedtest.asp", 
            "md5": "e7a84c58de7e4d36e7ac79581c33bcff", 
            "name": "speedtest", 
            "tar_url": "arm/speedtest/speedtest.tar.gz", 
            "title": "局域网测速", 
            "version": "0.0.4"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:11:58", 
            "description": "FileBrowser：您的可视化路由文件管理系统", 
            "home_url": "Module_filebrowser.asp", 
            "md5": "629c72d4ece51986c47f77748063d1c4", 
            "name": "filebrowser", 
            "tar_url": "arm/filebrowser/filebrowser.tar.gz", 
            "title": "filebrowser", 
            "version": "1.0.7"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:11:59", 
            "description": "去广告，没烦恼", 
            "home_url": "Module_koolproxy.asp", 
            "md5": "1b824de9d659aedb91bc6555a5a16506", 
            "name": "koolproxy", 
            "tar_url": "arm/koolproxy/koolproxy.tar.gz", 
            "title": "koolproxy", 
            "version": "3.8.5.6"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:11:59", 
            "description": "阿里云盘 WebDAV 服务器", 
            "home_url": "Module_aliyundrivewebdav.asp", 
            "md5": "9d450b4965e8601ec3ecc40b0b0c5fbb", 
            "name": "aliyundrivewebdav", 
            "tar_url": "arm/aliyundrivewebdav/aliyundrivewebdav.tar.gz", 
            "title": "阿里云盘WebDAV", 
            "version": "1.8.2"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:00", 
            "description": "老板，来一斤虚拟内存~", 
            "home_url": "Module_swap.asp", 
            "md5": "65e6280a219ae7c69f675c1c862f9f3b", 
            "name": "swap", 
            "tar_url": "arm/swap/swap.tar.gz", 
            "title": "虚拟内存", 
            "version": "2.6"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:00", 
            "description": "花生壳内网穿透", 
            "home_url": "Module_phddns.asp", 
            "md5": "f5b70904c11a3b9260307e870b13d500", 
            "name": "phddns", 
            "tar_url": "arm/phddns/phddns.tar.gz", 
            "title": "花生壳内网穿透", 
            "version": "3.0.6"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:01", 
            "description": "分布式的虚拟以太网", 
            "home_url": "Module_zerotier.asp", 
            "md5": "96516634d3d8bc610103b93547a49c30", 
            "name": "zerotier", 
            "tar_url": "arm/zerotier/zerotier.tar.gz", 
            "title": "zerotier", 
            "version": "1.6"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:02", 
            "description": "解锁网易云灰色歌曲", 
            "home_url": "Module_unblockmusic.asp", 
            "md5": "aee7c00c60dbb6da52eab49380231bb6", 
            "name": "unblockmusic", 
            "tar_url": "arm/unblockmusic/unblockmusic.tar.gz", 
            "title": "解锁网易云灰色歌曲", 
            "version": "1.2.1"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:02", 
            "description": "Cloudflare解析自动更新IP", 
            "home_url": "Module_cfddns.asp", 
            "md5": "f66488b2ca5661b819bd094f47df314a", 
            "name": "cfddns", 
            "tar_url": "arm/cfddns/cfddns.tar.gz", 
            "title": "Cloudflare DDNS", 
            "version": "1.9"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:02", 
            "description": "灵缇游戏加速插件", 
            "home_url": "Module_lingti.asp", 
            "md5": "51e53d05a0ae82acf5a9674efee3b271", 
            "name": "lingti", 
            "tar_url": "arm/lingti/lingti.tar.gz", 
            "title": "灵缇游戏加速插件", 
            "version": "1.0.3"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:02", 
            "description": "kms", 
            "home_url": "Module_kms.asp", 
            "md5": "129322e24d33394f64957d262661d267", 
            "name": "kms", 
            "tar_url": "arm/kms/kms.tar.gz", 
            "title": "系统工具", 
            "version": "2.0"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:03", 
            "description": "解决重启Bug", 
            "home_url": "Module_reboothelper.asp", 
            "md5": "1418a52b7bde4476004fe352fb766999", 
            "name": "reboothelper", 
            "tar_url": "arm/reboothelper/reboothelper.tar.gz", 
            "title": "重启助手", 
            "version": "0.5"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:03", 
            "description": "支持Alidns(阿里云) Dnspod(腾讯云) Cloudflare 华为云 Callback", 
            "home_url": "Module_ddns.asp", 
            "md5": "e8f11138ccf43b38e91fa0663130faa7", 
            "name": "ddns", 
            "tar_url": "arm/ddns/ddns.tar.gz", 
            "title": "多ddns合一", 
            "version": "0.3"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:03", 
            "description": "自己的私有云", 
            "home_url": "Module_verysync.asp", 
            "md5": "55682f4aef2c5b5b407fac8d10942b2e", 
            "name": "verysync", 
            "tar_url": "arm/verysync/verysync.tar.gz", 
            "title": "微力同步", 
            "version": "1.1.1"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:03", 
            "description": "自动部署SSL证书", 
            "home_url": "Module_acme.asp", 
            "md5": "09dc1b64fd898f14ab61d8d3cd710a5d", 
            "name": "acme", 
            "tar_url": "arm/acme/acme.tar.gz", 
            "title": "Let's Encrypt", 
            "version": "3.5"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:04", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frpc.asp", 
            "md5": "32e573696383e125e3621e2dd52a901c", 
            "name": "frpc", 
            "tar_url": "arm/frpc/frpc.tar.gz", 
            "title": "frpc穿透", 
            "version": "2.5"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:04", 
            "description": "aliddns", 
            "home_url": "Module_aliddns.asp", 
            "md5": "31bc63be9c7dd550a9c3448ac870d510", 
            "name": "aliddns", 
            "tar_url": "arm/aliddns/aliddns.tar.gz", 
            "title": "阿里DDNS", 
            "version": "2.6"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:04", 
            "description": "广告屏蔽大师 Plus 可以全面过滤各种横幅、弹窗、视频广告，同时阻止跟踪、隐私窃取及各种恶意网站", 
            "home_url": "Module_adbyby.asp", 
            "md5": "b1783b196a9e988669a22be5a13c224a", 
            "name": "adbyby", 
            "tar_url": "arm/adbyby/adbyby.tar.gz", 
            "title": "广告屏蔽大师 Plus", 
            "version": "1.4"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:05", 
            "description": "pppoe单线多拨，带宽提升神器！", 
            "home_url": "Module_mdial.asp", 
            "md5": "86300eff4012e3b02be0b01c6dfa22e8", 
            "name": "mdial", 
            "tar_url": "arm/mdial/mdial.tar.gz", 
            "title": "单线多拨", 
            "version": "1.7"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:05", 
            "description": "linux下载利器", 
            "home_url": "Module_aria2.asp", 
            "md5": "ed234e698ec1a576b346291e573a4227", 
            "name": "aria2", 
            "tar_url": "arm/aria2/aria2.tar.gz", 
            "title": "Aria2", 
            "version": "3.2"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:06", 
            "description": "Cloudflare Tunnel 客户端(以前称为 Argo Tunnel)", 
            "home_url": "Module_cloudflared.asp", 
            "md5": "30b28d3578052d377dcd7902577cf290", 
            "name": "cloudflared", 
            "tar_url": "arm/cloudflared/cloudflared.tar.gz", 
            "title": "cloudflared", 
            "version": "1.1"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:07", 
            "description": "这是一只自动帮你签到的dog", 
            "home_url": "Module_qiandao.asp", 
            "md5": "3010ff5169e8a9d7ca70439ba2afb1a4", 
            "name": "qiandao", 
            "tar_url": "arm/qiandao/qiandao.tar.gz", 
            "title": "签到dog", 
            "version": "1.8"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:08", 
            "description": "光猫助手: 快速设置，通过路由直接访问猫后台", 
            "home_url": "Module_lookcat.asp", 
            "md5": "a096cabec11a19d95d94cb7fb8af868a", 
            "name": "lookcat", 
            "tar_url": "arm/lookcat/lookcat.tar.gz", 
            "title": "光猫助手", 
            "version": "1.2"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:08", 
            "description": "超强的SSH网页客户端~", 
            "home_url": "Module_shellinabox.asp", 
            "md5": "97ff6b351053c364f4a8369492bf1eab", 
            "name": "shellinabox", 
            "tar_url": "arm/shellinabox/shellinabox.tar.gz", 
            "title": "shellinabox", 
            "version": "2.5"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:08", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_serverchan.asp", 
            "md5": "1dd63568c8a78c8cb8991eab63e05c79", 
            "name": "serverchan", 
            "tar_url": "arm/serverchan/serverchan.tar.gz", 
            "title": "ServerChan微信推送", 
            "version": "2.7"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:08", 
            "description": "使用Dnspod的ddns服务", 
            "home_url": "Module_ddnspod.asp", 
            "md5": "780f8847d8326b6dfc6bbbbe7ab1f8ee", 
            "name": "ddnspod", 
            "tar_url": "arm/ddnspod/ddnspod.tar.gz", 
            "title": "DDnspod", 
            "version": "2.0"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:09", 
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav，后端基于gin，前端使用react。", 
            "home_url": "Module_alist.asp", 
            "md5": "248c75d52febe3e465dc8c65934a9862", 
            "name": "alist", 
            "tar_url": "arm/alist/alist.tar.gz", 
            "title": "Alist文件列表", 
            "version": "1.9.2"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:13", 
            "description": "百度盘", 
            "home_url": "Module_baidupcs.asp", 
            "md5": "7d6819d0088dbe93ddbd863e92cb2498", 
            "name": "baidupcs", 
            "tar_url": "arm/baidupcs/baidupcs.tar.gz", 
            "title": "百度盘", 
            "version": "1.9"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:16", 
            "description": "DDNSTO远程控制", 
            "home_url": "Module_ddnsto.asp", 
            "md5": "f9e8676947ef3919fb7f9fd6682e9733", 
            "name": "ddnsto", 
            "tar_url": "arm/ddnsto/ddnsto.tar.gz", 
            "title": "DDNSTO远程控制", 
            "version": "3.0.3"
        }, 
        {
            "arch": "arm", 
            "build_date": "2024-10-31_14:12:16", 
            "description": "腾讯云ddns", 
            "home_url": "Module_tenddns.asp", 
            "md5": "9673ffa1df97d31b6c8461ad652870f9", 
            "name": "tenddns", 
            "tar_url": "arm/tenddns/tenddns.tar.gz", 
            "title": "腾讯云ddns", 
            "version": "0.0.4"
        }
    ], 
    "home_url": "https://raw.githubusercontent.com/SWRT-dev/softcenter/master", 
    "md5": "e3df55604a78e20861e90590beac75d8", 
    "tar_url": "arm/softcenter/softcenter.tar.gz", 
    "version": "1.5.4"
}