{
    "apps": [
        {
            "arch": "arm",
            "build_date": "2026-05-28_09:20:14",
            "description": "内网穿透利器，谁用谁知道。",
            "home_url": "Module_frps.asp",
            "md5": "281171638d605a84e524e897766c67b3",
            "name": "frps",
            "rc_support": "",
            "tar_url": "frps/frps.tar.gz",
            "title": "frps穿透服务器",
            "version": "2.3"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-29_10:01:52",
            "description": "简便高效的异地组网、内网穿透工具",
            "home_url": "Module_vnt.asp",
            "md5": "3b14646ac17a744fcd8e10c5af9cb677",
            "name": "vnt",
            "rc_support": "",
            "tar_url": "vnt/vnt.tar.gz",
            "title": "vnt",
            "version": "1.3"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-29_09:03:22",
            "description": "tailscale",
            "home_url": "Module_tailscale.asp",
            "md5": "a68fc62af60e45a7f73f0028c90b5ca9",
            "name": "tailscale",
            "rc_support": "",
            "tar_url": "tailscale/tailscale.tar.gz",
            "title": "tailscale",
            "version": "0.1.3"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-28_17:44:00",
            "description": "Socat 端口转发",
            "home_url": "Module_socat.asp",
            "md5": "49a1fc1a5286f7bf44964cf18d1c0a9f",
            "name": "socat",
            "rc_support": "",
            "tar_url": "socat/socat.tar.gz",
            "title": "Socat端口转发",
            "version": "1.3"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-28_20:19:55",
            "description": "VPN全家桶, ver 4.44 build 9807",
            "home_url": "Module_softether.asp",
            "md5": "5969218f68fd7d3936b65f80d4eddec3",
            "name": "softether",
            "rc_support": "",
            "tar_url": "softether/softether.tar.gz",
            "title": "SoftEther_VPN_Server",
            "version": "2.8"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-28_21:59:05",
            "description": "局域网网速测试工具",
            "home_url": "Module_speedtest.asp",
            "md5": "6a3fb509b5be354d30d80b4aab913f59",
            "name": "speedtest",
            "rc_support": "",
            "tar_url": "speedtest/speedtest.tar.gz",
            "title": "局域网测速",
            "version": "0.0.5"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-28_08:07:47",
            "description": "FileBrowser：您的可视化路由文件管理系统",
            "home_url": "Module_filebrowser.asp",
            "md5": "314a9ab7b54612d024cfc4fc58ed0964",
            "name": "filebrowser",
            "rc_support": "",
            "tar_url": "filebrowser/filebrowser.tar.gz",
            "title": "filebrowser",
            "version": "1.0.9"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-28_10:23:29",
            "description": "去广告，没烦恼",
            "home_url": "Module_koolproxy.asp",
            "md5": "f9a1517df7399f89cc4aa6b91f5aadaf",
            "name": "koolproxy",
            "rc_support": "",
            "tar_url": "koolproxy/koolproxy.tar.gz",
            "title": "koolproxy",
            "version": "3.8.5.7"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-26_15:22:22",
            "description": "阿里云盘 WebDAV 服务器",
            "home_url": "Module_aliyundrivewebdav.asp",
            "md5": "eb715a6860818c3730feb904712b9cff",
            "name": "aliyundrivewebdav",
            "rc_support": "",
            "tar_url": "aliyundrivewebdav/aliyundrivewebdav.tar.gz",
            "title": "阿里云盘WebDAV",
            "version": "1.8.3"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-29_08:46:53",
            "description": "老板，来一斤虚拟内存~",
            "home_url": "Module_swap.asp",
            "md5": "b99d8a38a1fee0264d75ceda1da690c0",
            "name": "swap",
            "rc_support": "",
            "tar_url": "swap/swap.tar.gz",
            "title": "虚拟内存",
            "version": "2.7"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-28_14:40:11",
            "description": "花生壳内网穿透",
            "home_url": "Module_phddns.asp",
            "md5": "a392ca306f54e200d8ec529647b9a04f",
            "name": "phddns",
            "rc_support": "",
            "tar_url": "phddns/phddns.tar.gz",
            "title": "花生壳内网穿透",
            "version": "3.0.7"
        },
        {
            "arch": "arm",
            "build_date": "2024-11-09_12:35:37",
            "description": "分布式的虚拟以太网",
            "home_url": "Module_zerotier.asp",
            "md5": "e6809476501b694f1d296bf820a71342",
            "name": "zerotier",
            "tar_url": "zerotier/zerotier.tar.gz",
            "title": "zerotier",
            "version": "1.6"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-29_10:03:40",
            "description": "解锁网易云灰色歌曲",
            "home_url": "Module_unblockmusic.asp",
            "md5": "1450d5e6dcc30886697aab12ba6acba9",
            "name": "unblockmusic",
            "rc_support": "",
            "tar_url": "unblockmusic/unblockmusic.tar.gz",
            "title": "解锁网易云灰色歌曲(go版)",
            "version": "1.2.2"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-26_21:19:00",
            "description": "Cloudflare解析自动更新IP",
            "home_url": "Module_cfddns.asp",
            "md5": "ae1b9aa54bf71e09aa9749669a769543",
            "name": "cfddns",
            "rc_support": "",
            "tar_url": "cfddns/cfddns.tar.gz",
            "title": "Cloudflare DDNS",
            "version": "2.0"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-28_12:11:19",
            "description": "灵缇游戏加速插件",
            "home_url": "Module_lingti.asp",
            "md5": "ce1ff9110a8a674169567855d33c3072",
            "name": "lingti",
            "rc_support": "",
            "tar_url": "lingti/lingti.tar.gz",
            "title": "灵缇游戏加速插件",
            "version": "1.0.4"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-28_12:53:00",
            "description": "lucky",
            "home_url": "Module_lucky.asp",
            "md5": "b3aa970833fc85b6642098e95d8bf6e5",
            "name": "lucky",
            "rc_support": "",
            "tar_url": "lucky/lucky.tar.gz",
            "title": "lucky",
            "version": "1.4.4"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-28_09:27:31",
            "description": "kms",
            "home_url": "Module_kms.asp",
            "md5": "b42e1159e915106b036c92dc7736be32",
            "name": "kms",
            "rc_support": "",
            "tar_url": "kms/kms.tar.gz",
            "title": "系统工具",
            "version": "2.1"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-28_15:24:06",
            "description": "解决重启Bug",
            "home_url": "Module_reboothelper.asp",
            "md5": "f33396bf8937ba44de1877c63cbf5c05",
            "name": "reboothelper",
            "rc_support": "",
            "tar_url": "reboothelper/reboothelper.tar.gz",
            "title": "重启助手",
            "version": "0.6"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-26_23:02:27",
            "description": "支持Alidns(阿里云) Dnspod(腾讯云) Cloudflare 华为云 Callback",
            "home_url": "Module_ddns.asp",
            "md5": "a07c11aabfdb1ccc8c9cbb9fa1843134",
            "name": "ddns",
            "rc_support": "",
            "tar_url": "ddns/ddns.tar.gz",
            "title": "多ddns合一",
            "version": "0.5"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-29_10:04:35",
            "description": "自己的私有云",
            "home_url": "Module_verysync.asp",
            "md5": "f843ee259e68cd025e9ea17df0bb4fdd",
            "name": "verysync",
            "rc_support": "",
            "tar_url": "verysync/verysync.tar.gz",
            "title": "微力同步",
            "version": "1.1.2"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-26_10:23:56",
            "description": "自动部署SSL证书",
            "home_url": "Module_acme.asp",
            "md5": "30ccae5a7ee72ef5ba9ea7f441cb82fa",
            "name": "acme",
            "rc_support": "",
            "tar_url": "acme/acme.tar.gz",
            "title": "Let's Encrypt",
            "version": "3.6"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-28_09:07:42",
            "description": "内网穿透利器，谁用谁知道。",
            "home_url": "Module_frpc.asp",
            "md5": "c66471c6cb32198397d4d8d601e593f5",
            "name": "frpc",
            "rc_support": "",
            "tar_url": "frpc/frpc.tar.gz",
            "title": "frpc穿透",
            "version": "2.7"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-26_13:02:18",
            "description": "aliddns",
            "home_url": "Module_aliddns.asp",
            "md5": "e92b500837db7c42b39e87e2ab67da8e",
            "name": "aliddns",
            "rc_support": "",
            "tar_url": "aliddns/aliddns.tar.gz",
            "title": "阿里DDNS",
            "version": "2.7"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-26_12:30:10",
            "description": "广告屏蔽大师 Plus 可以全面过滤各种横幅、弹窗、视频广告，同时阻止跟踪、隐私窃取及各种恶意网站",
            "home_url": "Module_adbyby.asp",
            "md5": "fa7fe73252411270b85ba1f5a16e7cf5",
            "name": "adbyby",
            "rc_support": "",
            "tar_url": "adbyby/adbyby.tar.gz",
            "title": "广告屏蔽大师 Plus",
            "version": "1.5"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-28_13:57:00",
            "description": "pppoe单线多拨，带宽提升神器！",
            "home_url": "Module_mdial.asp",
            "md5": "fff7dda084d8b6f8823091769f3c85db",
            "name": "mdial",
            "rc_support": "",
            "tar_url": "mdial/mdial.tar.gz",
            "title": "单线多拨",
            "version": "1.8"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-26_17:11:00",
            "description": "linux下载利器",
            "home_url": "Module_aria2.asp",
            "md5": "d6503a8d82da3b9ae1dc28008fc74551",
            "name": "aria2",
            "rc_support": "",
            "tar_url": "aria2/aria2.tar.gz",
            "title": "Aria2",
            "version": "3.3"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-26_21:48:45",
            "description": "Cloudflare Tunnel 客户端(以前称为 Argo Tunnel)",
            "home_url": "Module_cloudflared.asp",
            "md5": "2f1119dc91d88d9c2f26cc4910663a6c",
            "name": "cloudflared",
            "rc_support": "",
            "tar_url": "cloudflared/cloudflared.tar.gz",
            "title": "cloudflared",
            "version": "1.3"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-28_14:24:55",
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav。",
            "home_url": "Module_openlist.asp",
            "md5": "1a2fc05ff09b3dc864b1522209966913",
            "name": "openlist",
            "rc_support": "",
            "tar_url": "openlist/openlist.tar.gz",
            "title": "OpenList文件列表",
            "version": "1.2"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-28_12:35:11",
            "description": "光猫助手: 快速设置，通过路由直接访问猫后台",
            "home_url": "Module_lookcat.asp",
            "md5": "0792aaa012002aa9a1b06d691ca1089c",
            "name": "lookcat",
            "rc_support": "",
            "tar_url": "lookcat/lookcat.tar.gz",
            "title": "光猫助手",
            "version": "1.3"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-28_17:09:30",
            "description": "超强的SSH网页客户端~",
            "home_url": "Module_shellinabox.asp",
            "md5": "fc263fdf51e01e9021459454dc50346c",
            "name": "shellinabox",
            "rc_support": "",
            "tar_url": "shellinabox/shellinabox.tar.gz",
            "title": "shellinabox",
            "version": "2.6"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-28_16:25:05",
            "description": "从路由器推送状态及通知的工具",
            "home_url": "Module_serverchan.asp",
            "md5": "1c4c195be9c769b323026db571e84063",
            "name": "serverchan",
            "rc_support": "",
            "tar_url": "serverchan/serverchan.tar.gz",
            "title": "ServerChan微信推送",
            "version": "2.8"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-28_07:23:15",
            "description": "使用Dnspod的ddns服务",
            "home_url": "Module_ddnspod.asp",
            "md5": "061c592252006569d54a143cb88a69a2",
            "name": "ddnspod",
            "rc_support": "",
            "tar_url": "ddnspod/ddnspod.tar.gz",
            "title": "DDnspod",
            "version": "2.1"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-26_13:24:24",
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav，后端基于gin，前端使用react。",
            "home_url": "Module_alist.asp",
            "md5": "ae9acf2c4092e6330231c540cae90b70",
            "name": "alist",
            "rc_support": "",
            "tar_url": "alist/alist.tar.gz",
            "title": "Alist文件列表",
            "version": "1.9.3"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-26_18:42:40",
            "description": "百度盘",
            "home_url": "Module_baidupcs.asp",
            "md5": "0f8e48fe0c910c87f80a58e836af7c0d",
            "name": "baidupcs",
            "rc_support": "",
            "tar_url": "baidupcs/baidupcs.tar.gz",
            "title": "百度盘",
            "version": "2.0"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-28_07:34:15",
            "description": "DDNSTO远程控制",
            "home_url": "Module_ddnsto.asp",
            "md5": "4d19bfbc6b8dbbbdfc21e818d4491752",
            "name": "ddnsto",
            "rc_support": "",
            "tar_url": "ddnsto/ddnsto.tar.gz",
            "title": "DDNSTO远程控制",
            "version": "3.0.4"
        },
        {
            "arch": "arm",
            "build_date": "2026-05-29_10:03:03",
            "description": "腾讯云ddns",
            "home_url": "Module_tenddns.asp",
            "md5": "94b476070b4638f9cab0b12b653ba175",
            "name": "tenddns",
            "rc_support": "",
            "tar_url": "tenddns/tenddns.tar.gz",
            "title": "腾讯云ddns",
            "version": "0.0.5"
        }
    ],
    "home_url": "https://raw.githubusercontent.com/SWRT-dev/softcenter/master",
    "md5": "5a275f29d3972292d60493dd61d37328",
    "tar_url": "softcenter/softcenter.tar.gz",
    "version": "1.5.8"
}