{
    "apps": [
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:11:48", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frps.asp", 
            "md5": "b9478aba5efda9aa765c9c080b5afca3", 
            "name": "frps", 
            "tar_url": "mips/frps/frps.tar.gz", 
            "title": "frps穿透服务器", 
            "version": "2.1"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:11:49", 
            "description": "简便高效的异地组网、内网穿透工具", 
            "home_url": "Module_vnt.asp", 
            "md5": "08d7d835180be64f83afa8db6a7237d3", 
            "name": "vnt", 
            "tar_url": "mips/vnt/vnt.tar.gz", 
            "title": "vnt", 
            "version": "1.2"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:11:50", 
            "description": "node.js", 
            "home_url": "Module_node.asp", 
            "md5": "79b649e39b8cea2cbc1558a64fabcc1d", 
            "name": "node", 
            "tar_url": "mips/node/node.tar.gz", 
            "title": "node.js", 
            "version": "0.0.6"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:11:54", 
            "description": "tailscale", 
            "home_url": "Module_tailscale.asp", 
            "md5": "155cfb611e5fc01b1b048702f3db6d80", 
            "name": "tailscale", 
            "tar_url": "mips/tailscale/tailscale.tar.gz", 
            "title": "tailscale", 
            "version": "0.0.8"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:11:55", 
            "description": "Socat 端口转发", 
            "home_url": "Module_socat.asp", 
            "md5": "e9c372f977b7a524000241cfef6c1eb0", 
            "name": "socat", 
            "tar_url": "mips/socat/socat.tar.gz", 
            "title": "Socat端口转发", 
            "version": "1.1"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:11:56", 
            "description": "VPN全家桶, ver 4.30 build 9700", 
            "home_url": "", 
            "md5": "d398138af7df35d43c4b470ebddfd2f6", 
            "name": "softether", 
            "tar_url": "mips/softether/softether.tar.gz", 
            "title": "SoftEther_VPN_Server", 
            "version": "2.4"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:11:57", 
            "description": "局域网网速测试工具", 
            "home_url": "Module_speedtest.asp", 
            "md5": "3554567687e8feb843fd62dd1dae0c72", 
            "name": "speedtest", 
            "tar_url": "mips/speedtest/speedtest.tar.gz", 
            "title": "局域网测速", 
            "version": "0.0.4"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:11:58", 
            "description": "FileBrowser：您的可视化路由文件管理系统", 
            "home_url": "Module_filebrowser.asp", 
            "md5": "3bfad2f34ba39b2eb816cc898af92d44", 
            "name": "filebrowser", 
            "tar_url": "mips/filebrowser/filebrowser.tar.gz", 
            "title": "filebrowser", 
            "version": "1.0.7"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:11:59", 
            "description": "去广告，没烦恼", 
            "home_url": "Module_koolproxy.asp", 
            "md5": "5d9eb7cb87906530e0d66dcdad9afb0e", 
            "name": "koolproxy", 
            "tar_url": "mips/koolproxy/koolproxy.tar.gz", 
            "title": "koolproxy", 
            "version": "3.8.5.6"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:00", 
            "description": "阿里云盘 WebDAV 服务器", 
            "home_url": "Module_aliyundrivewebdav.asp", 
            "md5": "a0d3cf6473d0191b2e75f8cc7f6d060c", 
            "name": "aliyundrivewebdav", 
            "tar_url": "mips/aliyundrivewebdav/aliyundrivewebdav.tar.gz", 
            "title": "阿里云盘WebDAV", 
            "version": "1.8.2"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:00", 
            "description": "老板，来一斤虚拟内存~", 
            "home_url": "Module_swap.asp", 
            "md5": "cbc18223c6642755bba89f22941f7c1d", 
            "name": "swap", 
            "tar_url": "mips/swap/swap.tar.gz", 
            "title": "虚拟内存", 
            "version": "2.6"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:00", 
            "description": "花生壳内网穿透", 
            "home_url": "Module_phddns.asp", 
            "md5": "37557123444d243c3617b62f9ed24a88", 
            "name": "phddns", 
            "tar_url": "mips/phddns/phddns.tar.gz", 
            "title": "花生壳内网穿透", 
            "version": "3.0.6"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:01", 
            "description": "分布式的虚拟以太网", 
            "home_url": "Module_zerotier.asp", 
            "md5": "9b882ae4ea9e7284eb879b6cd13e4d85", 
            "name": "zerotier", 
            "tar_url": "mips/zerotier/zerotier.tar.gz", 
            "title": "zerotier", 
            "version": "1.6"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:02", 
            "description": "解锁网易云灰色歌曲", 
            "home_url": "Module_unblockmusic.asp", 
            "md5": "3b83b81493c6ff2cf9a6ae05a635a230", 
            "name": "unblockmusic", 
            "tar_url": "mips/unblockmusic/unblockmusic.tar.gz", 
            "title": "解锁网易云灰色歌曲", 
            "version": "1.2.1"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:02", 
            "description": "Cloudflare解析自动更新IP", 
            "home_url": "Module_cfddns.asp", 
            "md5": "ff5ccf64484d84a967404f0a37869400", 
            "name": "cfddns", 
            "tar_url": "mips/cfddns/cfddns.tar.gz", 
            "title": "Cloudflare DDNS", 
            "version": "1.9"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:02", 
            "description": "灵缇游戏加速插件", 
            "home_url": "Module_lingti.asp", 
            "md5": "2ea047d4b10d85fd0b1219b0244011df", 
            "name": "lingti", 
            "tar_url": "mips/lingti/lingti.tar.gz", 
            "title": "灵缇游戏加速插件", 
            "version": "1.0.3"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:03", 
            "description": "kms", 
            "home_url": "Module_kms.asp", 
            "md5": "89beed24e4331fbaf7045678c6db68f6", 
            "name": "kms", 
            "tar_url": "mips/kms/kms.tar.gz", 
            "title": "系统工具", 
            "version": "2.0"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:03", 
            "description": "解决重启Bug", 
            "home_url": "Module_reboothelper.asp", 
            "md5": "bcd1928ebe11408edbf9467166807726", 
            "name": "reboothelper", 
            "tar_url": "mips/reboothelper/reboothelper.tar.gz", 
            "title": "重启助手", 
            "version": "0.5"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:03", 
            "description": "支持Alidns(阿里云) Dnspod(腾讯云) Cloudflare 华为云 Callback", 
            "home_url": "Module_ddns.asp", 
            "md5": "457dada3fcdb1b7dbe4bb955b45525e6", 
            "name": "ddns", 
            "tar_url": "mips/ddns/ddns.tar.gz", 
            "title": "多ddns合一", 
            "version": "0.3"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:03", 
            "description": "自己的私有云", 
            "home_url": "Module_verysync.asp", 
            "md5": "04841c45f0368f776a56a6278465669b", 
            "name": "verysync", 
            "tar_url": "mips/verysync/verysync.tar.gz", 
            "title": "微力同步", 
            "version": "1.1.1"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:03", 
            "description": "自动部署SSL证书", 
            "home_url": "Module_acme.asp", 
            "md5": "09fc5888b3af7321cd11ac5ea8a88cc5", 
            "name": "acme", 
            "tar_url": "mips/acme/acme.tar.gz", 
            "title": "Let's Encrypt", 
            "version": "3.5"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:04", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frpc.asp", 
            "md5": "260b687bc1b478214e0a3c3a745dec14", 
            "name": "frpc", 
            "tar_url": "mips/frpc/frpc.tar.gz", 
            "title": "frpc穿透", 
            "version": "2.5"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:04", 
            "description": "aliddns", 
            "home_url": "Module_aliddns.asp", 
            "md5": "78990bcba609c5102a694dc868c354c5", 
            "name": "aliddns", 
            "tar_url": "mips/aliddns/aliddns.tar.gz", 
            "title": "阿里DDNS", 
            "version": "2.6"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:05", 
            "description": "广告屏蔽大师 Plus 可以全面过滤各种横幅、弹窗、视频广告，同时阻止跟踪、隐私窃取及各种恶意网站", 
            "home_url": "Module_adbyby.asp", 
            "md5": "efedebcf8259fc8eb77aab01ead43289", 
            "name": "adbyby", 
            "tar_url": "mips/adbyby/adbyby.tar.gz", 
            "title": "广告屏蔽大师 Plus", 
            "version": "1.4"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:05", 
            "description": "pppoe单线多拨，带宽提升神器！", 
            "home_url": "Module_mdial.asp", 
            "md5": "65e6e681241e0ef7cf7ef3c2c121e7cd", 
            "name": "mdial", 
            "tar_url": "mips/mdial/mdial.tar.gz", 
            "title": "单线多拨", 
            "version": "1.7"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:05", 
            "description": "linux下载利器", 
            "home_url": "Module_aria2.asp", 
            "md5": "4a511cbb0f0b883650f4ae898422e66f", 
            "name": "aria2", 
            "tar_url": "mips/aria2/aria2.tar.gz", 
            "title": "Aria2", 
            "version": "3.2"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:06", 
            "description": "Intel CPU频率设置", 
            "home_url": "Module_cpufreq.asp", 
            "md5": "3eed54f7fd2c078473e15454e0b65005", 
            "name": "cpufreq", 
            "tar_url": "mips/cpufreq/cpufreq.tar.gz", 
            "title": "CPU频率设置", 
            "version": "1.1"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:06", 
            "description": "Cloudflare Tunnel 客户端(以前称为 Argo Tunnel)", 
            "home_url": "Module_cloudflared.asp", 
            "md5": "2187c818a0ea1247997ed25ddf5dc06a", 
            "name": "cloudflared", 
            "tar_url": "mips/cloudflared/cloudflared.tar.gz", 
            "title": "cloudflared", 
            "version": "1.1"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:07", 
            "description": "这是一只自动帮你签到的dog", 
            "home_url": "Module_qiandao.asp", 
            "md5": "8b00de2cda7590995eb5a5aa1c373570", 
            "name": "qiandao", 
            "tar_url": "mips/qiandao/qiandao.tar.gz", 
            "title": "签到dog", 
            "version": "1.8"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:08", 
            "description": "光猫助手: 快速设置，通过路由直接访问猫后台", 
            "home_url": "Module_lookcat.asp", 
            "md5": "563041fccda6331291c4d5388c8076d8", 
            "name": "lookcat", 
            "tar_url": "mips/lookcat/lookcat.tar.gz", 
            "title": "光猫助手", 
            "version": "1.2"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:08", 
            "description": "超强的SSH网页客户端~", 
            "home_url": "Module_shellinabox.asp", 
            "md5": "34a2e0c33a48191d47eafe45b08caf0b", 
            "name": "shellinabox", 
            "tar_url": "mips/shellinabox/shellinabox.tar.gz", 
            "title": "shellinabox", 
            "version": "2.5"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:08", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_serverchan.asp", 
            "md5": "ba6495f1d019c334cdb7a386a416e4c4", 
            "name": "serverchan", 
            "tar_url": "mips/serverchan/serverchan.tar.gz", 
            "title": "ServerChan微信推送", 
            "version": "2.7"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:08", 
            "description": "使用Dnspod的ddns服务", 
            "home_url": "Module_ddnspod.asp", 
            "md5": "d383968e704e7150be52b46a63ce0842", 
            "name": "ddnspod", 
            "tar_url": "mips/ddnspod/ddnspod.tar.gz", 
            "title": "DDnspod", 
            "version": "2.0"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:12", 
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav，后端基于gin，前端使用react。", 
            "home_url": "Module_alist.asp", 
            "md5": "3a49bef0a58da942f81aa295383ef73d", 
            "name": "alist", 
            "tar_url": "mips/alist/alist.tar.gz", 
            "title": "Alist文件列表", 
            "version": "1.9.2"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:15", 
            "description": "百度盘", 
            "home_url": "Module_baidupcs.asp", 
            "md5": "3b9c43446cb20554f71ab7655d6e9529", 
            "name": "baidupcs", 
            "tar_url": "mips/baidupcs/baidupcs.tar.gz", 
            "title": "百度盘", 
            "version": "1.9"
        }, 
        {
            "arch": "mips", 
            "build_date": "2024-10-31_14:12:16", 
            "description": "腾讯云ddns", 
            "home_url": "Module_tenddns.asp", 
            "md5": "97617d101fdcd0d620f87a5efcd91c8f", 
            "name": "tenddns", 
            "tar_url": "mips/tenddns/tenddns.tar.gz", 
            "title": "腾讯云ddns", 
            "version": "0.0.4"
        }
    ], 
    "home_url": "https://raw.githubusercontent.com/SWRT-dev/softcenter/master", 
    "md5": "8bbd332c45c13284496c72bdaff09905", 
    "tar_url": "mips/softcenter/softcenter.tar.gz", 
    "version": "1.5.4"
}