{
    "apps": [
        {
            "arch": "mips",
            "build_date": "2025-09-05_14:32:45",
            "description": "内网穿透利器，谁用谁知道。",
            "home_url": "Module_frps.asp",
            "md5": "2ac87fe93d617035b0de5c79a8ae02bc",
            "name": "frps",
            "tar_url": "frps/frps.tar.gz",
            "title": "frps穿透服务器",
            "version": "2.2"
        },
        {
            "arch": "mips",
            "build_date": "2024-11-09_12:35:20",
            "description": "简便高效的异地组网、内网穿透工具",
            "home_url": "Module_vnt.asp",
            "md5": "764f262cc93f9bb0d6400dd0d50648e8",
            "name": "vnt",
            "tar_url": "vnt/vnt.tar.gz",
            "title": "vnt",
            "version": "1.2"
        },
        {
            "arch": "mips",
            "build_date": "2024-11-09_12:35:22",
            "description": "node.js",
            "home_url": "Module_node.asp",
            "md5": "af3f58860faa62f26f735ff030850a6d",
            "name": "node",
            "tar_url": "node/node.tar.gz",
            "title": "node.js",
            "version": "0.0.6"
        },
        {
            "arch": "mips",
            "build_date": "2026-01-10_15:26:22",
            "description": "tailscale",
            "home_url": "Module_tailscale.asp",
            "md5": "a2c4360460e54986ab64bbe71141c420",
            "name": "tailscale",
            "tar_url": "tailscale/tailscale.tar.gz",
            "title": "tailscale",
            "version": "0.1.2"
        },
        {
            "arch": "mips",
            "build_date": "2025-09-04_22:50:38",
            "description": "Socat 端口转发",
            "home_url": "Module_socat.asp",
            "md5": "124e6be8480b1f63d93d74378e646ce0",
            "name": "socat",
            "tar_url": "socat/socat.tar.gz",
            "title": "Socat端口转发",
            "version": "1.2"
        },
        {
            "arch": "mips",
            "build_date": "2025-12-31_08:55:19",
            "description": "VPN全家桶, ver 4.44 build 9807",
            "home_url": "",
            "md5": "5f4e632a3088293bcc5bb44c87880299",
            "name": "softether",
            "tar_url": "softether/softether.tar.gz",
            "title": "SoftEther_VPN_Server",
            "version": "2.7"
        },
        {
            "arch": "mips",
            "build_date": "2024-11-09_12:35:32",
            "description": "局域网网速测试工具",
            "home_url": "Module_speedtest.asp",
            "md5": "78c5b802ab7dbb21e6c1f392bdf42b84",
            "name": "speedtest",
            "tar_url": "speedtest/speedtest.tar.gz",
            "title": "局域网测速",
            "version": "0.0.4"
        },
        {
            "arch": "mips",
            "build_date": "2026-05-28_08:07:48",
            "description": "FileBrowser：您的可视化路由文件管理系统",
            "home_url": "Module_filebrowser.asp",
            "md5": "d5e6f468db65ebab1005ba53f47e4252",
            "name": "filebrowser",
            "rc_support": "",
            "tar_url": "filebrowser/filebrowser.tar.gz",
            "title": "filebrowser",
            "version": "1.0.9"
        },
        {
            "arch": "mips",
            "build_date": "2024-11-09_12:35:34",
            "description": "去广告，没烦恼",
            "home_url": "Module_koolproxy.asp",
            "md5": "b7bb2724d82dc95ca6b956f077c7efc6",
            "name": "koolproxy",
            "tar_url": "koolproxy/koolproxy.tar.gz",
            "title": "koolproxy",
            "version": "3.8.5.6"
        },
        {
            "arch": "mips",
            "build_date": "2026-05-26_15:22:23",
            "description": "阿里云盘 WebDAV 服务器",
            "home_url": "Module_aliyundrivewebdav.asp",
            "md5": "8d3c35dbca5e8b0eaedafcdbb2f432b6",
            "name": "aliyundrivewebdav",
            "rc_support": "",
            "tar_url": "aliyundrivewebdav/aliyundrivewebdav.tar.gz",
            "title": "阿里云盘WebDAV",
            "version": "1.8.3"
        },
        {
            "arch": "mips",
            "build_date": "2024-11-09_12:35:36",
            "description": "老板，来一斤虚拟内存~",
            "home_url": "Module_swap.asp",
            "md5": "2a6734746ac15e2e8be2d0bfbed40d62",
            "name": "swap",
            "tar_url": "swap/swap.tar.gz",
            "title": "虚拟内存",
            "version": "2.6"
        },
        {
            "arch": "mips",
            "build_date": "2024-11-09_12:35:36",
            "description": "花生壳内网穿透",
            "home_url": "Module_phddns.asp",
            "md5": "c47f900db352d20e5922e988e60ddc8b",
            "name": "phddns",
            "tar_url": "phddns/phddns.tar.gz",
            "title": "花生壳内网穿透",
            "version": "3.0.6"
        },
        {
            "arch": "mips",
            "build_date": "2024-11-09_12:35:37",
            "description": "分布式的虚拟以太网",
            "home_url": "Module_zerotier.asp",
            "md5": "622f4ce0fa7954d6663610348134689c",
            "name": "zerotier",
            "tar_url": "zerotier/zerotier.tar.gz",
            "title": "zerotier",
            "version": "1.6"
        },
        {
            "arch": "mips",
            "build_date": "2024-11-09_12:35:38",
            "description": "解锁网易云灰色歌曲",
            "home_url": "Module_unblockmusic.asp",
            "md5": "a326d9c1b8284cd29d1a0e7ca93a1afb",
            "name": "unblockmusic",
            "tar_url": "unblockmusic/unblockmusic.tar.gz",
            "title": "解锁网易云灰色歌曲",
            "version": "1.2.1"
        },
        {
            "arch": "mips",
            "build_date": "2026-05-26_21:19:00",
            "description": "Cloudflare解析自动更新IP",
            "home_url": "Module_cfddns.asp",
            "md5": "7695e84ed38eb96adbff6a07bffa5210",
            "name": "cfddns",
            "rc_support": "",
            "tar_url": "cfddns/cfddns.tar.gz",
            "title": "Cloudflare DDNS",
            "version": "2.0"
        },
        {
            "arch": "mips",
            "build_date": "2024-11-09_12:35:39",
            "description": "灵缇游戏加速插件",
            "home_url": "Module_lingti.asp",
            "md5": "6b371d82197271c4ef52cd9bf387a908",
            "name": "lingti",
            "tar_url": "lingti/lingti.tar.gz",
            "title": "灵缇游戏加速插件",
            "version": "1.0.3"
        },
        {
            "arch": "mips",
            "build_date": "2025-03-23_14:29:52",
            "description": "lucky",
            "home_url": "Module_lucky.asp",
            "md5": "0a5a1705b806347efac7bbdd7594a28c",
            "name": "lucky",
            "tar_url": "lucky/lucky.tar.gz",
            "title": "lucky",
            "version": "1.4.3"
        },
        {
            "arch": "mips",
            "build_date": "2024-11-09_12:35:39",
            "description": "kms",
            "home_url": "Module_kms.asp",
            "md5": "e9e1334f302dccbc526f5ff3b371a2fd",
            "name": "kms",
            "tar_url": "kms/kms.tar.gz",
            "title": "系统工具",
            "version": "2.0"
        },
        {
            "arch": "mips",
            "build_date": "2024-11-09_12:35:40",
            "description": "解决重启Bug",
            "home_url": "Module_reboothelper.asp",
            "md5": "dec0cd8367ccb0d2ffce0d7aa0c9b0c5",
            "name": "reboothelper",
            "tar_url": "reboothelper/reboothelper.tar.gz",
            "title": "重启助手",
            "version": "0.5"
        },
        {
            "arch": "mips",
            "build_date": "2026-05-26_23:02:27",
            "description": "支持Alidns(阿里云) Dnspod(腾讯云) Cloudflare 华为云 Callback",
            "home_url": "Module_ddns.asp",
            "md5": "cd13b1ba3ab7aaafeada91bf1b6d2922",
            "name": "ddns",
            "rc_support": "",
            "tar_url": "ddns/ddns.tar.gz",
            "title": "多ddns合一",
            "version": "0.5"
        },
        {
            "arch": "mips",
            "build_date": "2024-11-09_12:35:40",
            "description": "自己的私有云",
            "home_url": "Module_verysync.asp",
            "md5": "250cc5d99be3978c01115f0c87eb640e",
            "name": "verysync",
            "tar_url": "verysync/verysync.tar.gz",
            "title": "微力同步",
            "version": "1.1.1"
        },
        {
            "arch": "mips",
            "build_date": "2026-05-26_10:23:56",
            "description": "自动部署SSL证书",
            "home_url": "Module_acme.asp",
            "md5": "4e8b9ce3387ab27e64db640d32982c08",
            "name": "acme",
            "rc_support": "",
            "tar_url": "acme/acme.tar.gz",
            "title": "Let's Encrypt",
            "version": "3.6"
        },
        {
            "arch": "mips",
            "build_date": "2025-09-05_14:30:20",
            "description": "内网穿透利器，谁用谁知道。",
            "home_url": "Module_frpc.asp",
            "md5": "4bd5fb25d4ac9dc2b8186826c656037f",
            "name": "frpc",
            "tar_url": "frpc/frpc.tar.gz",
            "title": "frpc穿透",
            "version": "2.6"
        },
        {
            "arch": "mips",
            "build_date": "2026-05-26_13:02:18",
            "description": "aliddns",
            "home_url": "Module_aliddns.asp",
            "md5": "4b832aff10b2e42b1b7dc4bc9675d43b",
            "name": "aliddns",
            "rc_support": "",
            "tar_url": "aliddns/aliddns.tar.gz",
            "title": "阿里DDNS",
            "version": "2.7"
        },
        {
            "arch": "mips",
            "build_date": "2026-05-26_12:30:10",
            "description": "广告屏蔽大师 Plus 可以全面过滤各种横幅、弹窗、视频广告，同时阻止跟踪、隐私窃取及各种恶意网站",
            "home_url": "Module_adbyby.asp",
            "md5": "464708f06a6583b8c42453a3ce83eefe",
            "name": "adbyby",
            "rc_support": "",
            "tar_url": "adbyby/adbyby.tar.gz",
            "title": "广告屏蔽大师 Plus",
            "version": "1.5"
        },
        {
            "arch": "mips",
            "build_date": "2024-11-09_12:35:43",
            "description": "pppoe单线多拨，带宽提升神器！",
            "home_url": "Module_mdial.asp",
            "md5": "26cfa92842c24feb677e135f85ad1538",
            "name": "mdial",
            "tar_url": "mdial/mdial.tar.gz",
            "title": "单线多拨",
            "version": "1.7"
        },
        {
            "arch": "mips",
            "build_date": "2026-05-26_17:11:00",
            "description": "linux下载利器",
            "home_url": "Module_aria2.asp",
            "md5": "7b048e035ac2afa7b963c3c99f2089f9",
            "name": "aria2",
            "rc_support": "",
            "tar_url": "aria2/aria2.tar.gz",
            "title": "Aria2",
            "version": "3.3"
        },
        {
            "arch": "mips",
            "build_date": "2026-05-26_22:46:26",
            "description": "Intel CPU频率设置",
            "home_url": "Module_cpufreq.asp",
            "md5": "b1a41a43f8dfd653b4ee647f7fca295a",
            "name": "cpufreq",
            "rc_support": "amas",
            "tar_url": "cpufreq/cpufreq.tar.gz",
            "title": "CPU频率设置",
            "version": "1.3"
        },
        {
            "arch": "mips",
            "build_date": "2026-05-26_21:48:46",
            "description": "Cloudflare Tunnel 客户端(以前称为 Argo Tunnel)",
            "home_url": "Module_cloudflared.asp",
            "md5": "bae430bf7d1ebf9cd54d1ba10bfed8ae",
            "name": "cloudflared",
            "rc_support": "",
            "tar_url": "cloudflared/cloudflared.tar.gz",
            "title": "cloudflared",
            "version": "1.3"
        },
        {
            "arch": "mips",
            "build_date": "2024-11-09_12:35:46",
            "description": "这是一只自动帮你签到的dog",
            "home_url": "Module_qiandao.asp",
            "md5": "35e7a6b1cc4d675caf572415d19220f4",
            "name": "qiandao",
            "tar_url": "qiandao/qiandao.tar.gz",
            "title": "签到dog",
            "version": "1.8"
        },
        {
            "arch": "mips",
            "build_date": "2025-09-08_09:14:21",
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav。",
            "home_url": "Module_openlist.asp",
            "md5": "c90ff1e51717745468e9ad38459f0386",
            "name": "openlist",
            "tar_url": "openlist/openlist.tar.gz",
            "title": "OpenList文件列表",
            "version": "1.1"
        },
        {
            "arch": "mips",
            "build_date": "2024-11-09_12:35:47",
            "description": "光猫助手: 快速设置，通过路由直接访问猫后台",
            "home_url": "Module_lookcat.asp",
            "md5": "2fa19012d15ba5bb6bf37bb4b18eaebb",
            "name": "lookcat",
            "tar_url": "lookcat/lookcat.tar.gz",
            "title": "光猫助手",
            "version": "1.2"
        },
        {
            "arch": "mips",
            "build_date": "2025-09-04_22:51:58",
            "description": "超强的SSH网页客户端~",
            "home_url": "Module_shellinabox.asp",
            "md5": "400db704e641b710e5ae042f738e1a07",
            "name": "shellinabox",
            "tar_url": "shellinabox/shellinabox.tar.gz",
            "title": "shellinabox",
            "version": "2.5"
        },
        {
            "arch": "mips",
            "build_date": "2024-11-09_12:35:47",
            "description": "从路由器推送状态及通知的工具",
            "home_url": "Module_serverchan.asp",
            "md5": "df3ff4cf34dcbf711334982b2f1ca183",
            "name": "serverchan",
            "tar_url": "serverchan/serverchan.tar.gz",
            "title": "ServerChan微信推送",
            "version": "2.7"
        },
        {
            "arch": "mips",
            "build_date": "2026-05-28_07:23:16",
            "description": "使用Dnspod的ddns服务",
            "home_url": "Module_ddnspod.asp",
            "md5": "6bf0493fff5a7a97f000c2e4eed1b45a",
            "name": "ddnspod",
            "rc_support": "",
            "tar_url": "ddnspod/ddnspod.tar.gz",
            "title": "DDnspod",
            "version": "2.1"
        },
        {
            "arch": "mips",
            "build_date": "2026-05-26_13:24:27",
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav，后端基于gin，前端使用react。",
            "home_url": "Module_alist.asp",
            "md5": "677605fa38051d97d04198fc4aae5c78",
            "name": "alist",
            "rc_support": "",
            "tar_url": "alist/alist.tar.gz",
            "title": "Alist文件列表",
            "version": "1.9.3"
        },
        {
            "arch": "mips",
            "build_date": "2026-05-26_18:42:42",
            "description": "百度盘",
            "home_url": "Module_baidupcs.asp",
            "md5": "1af0107fc9bc0632c80d20f0e9bb466f",
            "name": "baidupcs",
            "rc_support": "",
            "tar_url": "baidupcs/baidupcs.tar.gz",
            "title": "百度盘",
            "version": "2.0"
        },
        {
            "arch": "mips",
            "build_date": "2024-11-09_12:35:59",
            "description": "腾讯云ddns",
            "home_url": "Module_tenddns.asp",
            "md5": "543399ac1bf7b24b74680a6949b88581",
            "name": "tenddns",
            "tar_url": "tenddns/tenddns.tar.gz",
            "title": "腾讯云ddns",
            "version": "0.0.4"
        }
    ],
    "home_url": "https://raw.githubusercontent.com/SWRT-dev/softcenter/master",
    "md5": "725c9e216e4c9a1be40441d77ba9eb79",
    "tar_url": "softcenter/softcenter.tar.gz",
    "version": "1.5.8"
}