{
    "apps": [
        {
            "arch": "arm64", 
            "build_date": "2025-09-05_09:21:11", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frps.asp", 
            "md5": "77042d0e728710c4828345b6334b9b1c", 
            "name": "frps", 
            "tar_url": "frps/frps.tar.gz", 
            "title": "frps穿透服务器", 
            "version": "2.2"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:20", 
            "description": "简便高效的异地组网、内网穿透工具", 
            "home_url": "Module_vnt.asp", 
            "md5": "c445caa892b8e3e6dd2dd72a1b68b2c1", 
            "name": "vnt", 
            "tar_url": "vnt/vnt.tar.gz", 
            "title": "vnt", 
            "version": "1.2"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:21", 
            "description": "node.js", 
            "home_url": "Module_node.asp", 
            "md5": "bdea08b9c9cbaa7026773fbbe60426f1", 
            "name": "node", 
            "tar_url": "node/node.tar.gz", 
            "title": "node.js", 
            "version": "0.0.6"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2025-03-08_15:54:15", 
            "description": "tailscale", 
            "home_url": "Module_tailscale.asp", 
            "md5": "0d88d410dd2454b5d28b83be6dbc5e43", 
            "name": "tailscale", 
            "tar_url": "tailscale/tailscale.tar.gz", 
            "title": "tailscale", 
            "version": "0.0.9"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2025-09-04_22:50:38", 
            "description": "Socat 端口转发", 
            "home_url": "Module_socat.asp", 
            "md5": "052a63b2b79b869582ca6d77bfdf500e", 
            "name": "socat", 
            "tar_url": "socat/socat.tar.gz", 
            "title": "Socat端口转发", 
            "version": "1.2"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2025-09-04_22:17:24", 
            "description": "VPN全家桶, ver 4.44 build 9807", 
            "home_url": "", 
            "md5": "f97edb2bf8705e72a33eb8c8c664945b", 
            "name": "softether", 
            "tar_url": "softether/softether.tar.gz", 
            "title": "SoftEther_VPN_Server", 
            "version": "2.5"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:32", 
            "description": "局域网网速测试工具", 
            "home_url": "Module_speedtest.asp", 
            "md5": "42c8d2fa839eea63902e04bc0254c5cf", 
            "name": "speedtest", 
            "tar_url": "speedtest/speedtest.tar.gz", 
            "title": "局域网测速", 
            "version": "0.0.4"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:33", 
            "description": "FileBrowser：您的可视化路由文件管理系统", 
            "home_url": "Module_filebrowser.asp", 
            "md5": "49b1c796cbb77357ffd3fa75b0854841", 
            "name": "filebrowser", 
            "tar_url": "filebrowser/filebrowser.tar.gz", 
            "title": "filebrowser", 
            "version": "1.0.7"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:34", 
            "description": "去广告，没烦恼", 
            "home_url": "Module_koolproxy.asp", 
            "md5": "8e434c4b638c77d12645ed05a47bdca1", 
            "name": "koolproxy", 
            "tar_url": "koolproxy/koolproxy.tar.gz", 
            "title": "koolproxy", 
            "version": "3.8.5.6"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:35", 
            "description": "阿里云盘 WebDAV 服务器", 
            "home_url": "Module_aliyundrivewebdav.asp", 
            "md5": "af1edaf594c9eab0ad3d3f86e23837ce", 
            "name": "aliyundrivewebdav", 
            "tar_url": "aliyundrivewebdav/aliyundrivewebdav.tar.gz", 
            "title": "阿里云盘WebDAV", 
            "version": "1.8.2"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:36", 
            "description": "老板，来一斤虚拟内存~", 
            "home_url": "Module_swap.asp", 
            "md5": "43a18497312cd7eddb3e7877c593c992", 
            "name": "swap", 
            "tar_url": "swap/swap.tar.gz", 
            "title": "虚拟内存", 
            "version": "2.6"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:36", 
            "description": "花生壳内网穿透", 
            "home_url": "Module_phddns.asp", 
            "md5": "3b64366f908dda13cf1ba1aa1f5b0529", 
            "name": "phddns", 
            "tar_url": "phddns/phddns.tar.gz", 
            "title": "花生壳内网穿透", 
            "version": "3.0.6"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:37", 
            "description": "分布式的虚拟以太网", 
            "home_url": "Module_zerotier.asp", 
            "md5": "eee415891aa13de4ffb09596a5fe79eb", 
            "name": "zerotier", 
            "tar_url": "zerotier/zerotier.tar.gz", 
            "title": "zerotier", 
            "version": "1.6"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:38", 
            "description": "解锁网易云灰色歌曲", 
            "home_url": "Module_unblockmusic.asp", 
            "md5": "487f26628e509ed1ebae23e335208b41", 
            "name": "unblockmusic", 
            "tar_url": "unblockmusic/unblockmusic.tar.gz", 
            "title": "解锁网易云灰色歌曲", 
            "version": "1.2.1"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:39", 
            "description": "Cloudflare解析自动更新IP", 
            "home_url": "Module_cfddns.asp", 
            "md5": "c4a2079841f907554896c0f8be76f0d3", 
            "name": "cfddns", 
            "tar_url": "cfddns/cfddns.tar.gz", 
            "title": "Cloudflare DDNS", 
            "version": "1.9"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:39", 
            "description": "灵缇游戏加速插件", 
            "home_url": "Module_lingti.asp", 
            "md5": "52770c43dd5e7ddc752616f2676baf94", 
            "name": "lingti", 
            "tar_url": "lingti/lingti.tar.gz", 
            "title": "灵缇游戏加速插件", 
            "version": "1.0.3"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2025-03-23_14:29:52", 
            "description": "lucky", 
            "home_url": "Module_lucky.asp", 
            "md5": "751bd20fe82ce599200cce5d1f1289f9", 
            "name": "lucky", 
            "tar_url": "lucky/lucky.tar.gz", 
            "title": "lucky", 
            "version": "1.4.3"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:39", 
            "description": "kms", 
            "home_url": "Module_kms.asp", 
            "md5": "26d6d01032ffdf9a86e447fd387c63c5", 
            "name": "kms", 
            "tar_url": "kms/kms.tar.gz", 
            "title": "系统工具", 
            "version": "2.0"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:40", 
            "description": "解决重启Bug", 
            "home_url": "Module_reboothelper.asp", 
            "md5": "139027b068c7530f6befdbb8b9ccb003", 
            "name": "reboothelper", 
            "tar_url": "reboothelper/reboothelper.tar.gz", 
            "title": "重启助手", 
            "version": "0.5"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2025-09-04_08:16:21", 
            "description": "支持Alidns(阿里云) Dnspod(腾讯云) Cloudflare 华为云 Callback", 
            "home_url": "Module_ddns.asp", 
            "md5": "dfad22e3c4f64a884c3187f1acd4e13c", 
            "name": "ddns", 
            "tar_url": "ddns/ddns.tar.gz", 
            "title": "多ddns合一", 
            "version": "0.4"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:40", 
            "description": "自己的私有云", 
            "home_url": "Module_verysync.asp", 
            "md5": "2a4d7a225bbb38e22814ee24096a0000", 
            "name": "verysync", 
            "tar_url": "verysync/verysync.tar.gz", 
            "title": "微力同步", 
            "version": "1.1.1"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:41", 
            "description": "自动部署SSL证书", 
            "home_url": "Module_acme.asp", 
            "md5": "53ebdfd3bd9f2b1c7d2ce67216e3180b", 
            "name": "acme", 
            "tar_url": "acme/acme.tar.gz", 
            "title": "Let's Encrypt", 
            "version": "3.5"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:41", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frpc.asp", 
            "md5": "77c364e7af826c349f7366743b6421e0", 
            "name": "frpc", 
            "tar_url": "frpc/frpc.tar.gz", 
            "title": "frpc穿透", 
            "version": "2.5"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:42", 
            "description": "aliddns", 
            "home_url": "Module_aliddns.asp", 
            "md5": "4623b9e93e403df9db696840b5c57717", 
            "name": "aliddns", 
            "tar_url": "aliddns/aliddns.tar.gz", 
            "title": "阿里DDNS", 
            "version": "2.6"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:42", 
            "description": "广告屏蔽大师 Plus 可以全面过滤各种横幅、弹窗、视频广告，同时阻止跟踪、隐私窃取及各种恶意网站", 
            "home_url": "Module_adbyby.asp", 
            "md5": "b76a447aaa8d53283c3567d5748c3f98", 
            "name": "adbyby", 
            "tar_url": "adbyby/adbyby.tar.gz", 
            "title": "广告屏蔽大师 Plus", 
            "version": "1.4"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:43", 
            "description": "pppoe单线多拨，带宽提升神器！", 
            "home_url": "Module_mdial.asp", 
            "md5": "43b1c7ca2ccdeb50845bceddc69e9024", 
            "name": "mdial", 
            "tar_url": "mdial/mdial.tar.gz", 
            "title": "单线多拨", 
            "version": "1.7"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:43", 
            "description": "linux下载利器", 
            "home_url": "Module_aria2.asp", 
            "md5": "2bd8f7fc84027642d3c70c9bcd9d1665", 
            "name": "aria2", 
            "tar_url": "aria2/aria2.tar.gz", 
            "title": "Aria2", 
            "version": "3.2"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-12-04_18:20:21", 
            "description": "Cloudflare Tunnel 客户端(以前称为 Argo Tunnel)", 
            "home_url": "Module_cloudflared.asp", 
            "md5": "32feef7e0d45e08304f0ed8997ded78e", 
            "name": "cloudflared", 
            "tar_url": "cloudflared/cloudflared.tar.gz", 
            "title": "cloudflared", 
            "version": "1.2"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:46", 
            "description": "这是一只自动帮你签到的dog", 
            "home_url": "Module_qiandao.asp", 
            "md5": "9e6294ac7b832be4cd3708bfa81e4151", 
            "name": "qiandao", 
            "tar_url": "qiandao/qiandao.tar.gz", 
            "title": "签到dog", 
            "version": "1.8"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2025-09-04_12:06:47", 
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav。", 
            "home_url": "Module_openlist.asp", 
            "md5": "84d25f1a3df3a6ac4193b97bac96decf", 
            "name": "openlist", 
            "tar_url": "openlist/openlist.tar.gz", 
            "title": "OpenList文件列表", 
            "version": "1.0"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:47", 
            "description": "光猫助手: 快速设置，通过路由直接访问猫后台", 
            "home_url": "Module_lookcat.asp", 
            "md5": "273235fc2d7a9c852e147dd0f33f7193", 
            "name": "lookcat", 
            "tar_url": "lookcat/lookcat.tar.gz", 
            "title": "光猫助手", 
            "version": "1.2"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2025-09-04_22:51:58", 
            "description": "超强的SSH网页客户端~", 
            "home_url": "Module_shellinabox.asp", 
            "md5": "97de938b27ca6e1883895cea35fbf3dc", 
            "name": "shellinabox", 
            "tar_url": "shellinabox/shellinabox.tar.gz", 
            "title": "shellinabox", 
            "version": "2.5"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:47", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_serverchan.asp", 
            "md5": "fa680490a79fc9cc9ac944458beffe0b", 
            "name": "serverchan", 
            "tar_url": "serverchan/serverchan.tar.gz", 
            "title": "ServerChan微信推送", 
            "version": "2.7"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:48", 
            "description": "使用Dnspod的ddns服务", 
            "home_url": "Module_ddnspod.asp", 
            "md5": "6e28094ff8e79b10b076ac7cb7fa16c1", 
            "name": "ddnspod", 
            "tar_url": "ddnspod/ddnspod.tar.gz", 
            "title": "DDnspod", 
            "version": "2.0"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:52", 
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav，后端基于gin，前端使用react。", 
            "home_url": "Module_alist.asp", 
            "md5": "42c71648f83dc4d3794fc12f544d1db1", 
            "name": "alist", 
            "tar_url": "alist/alist.tar.gz", 
            "title": "Alist文件列表", 
            "version": "1.9.2"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:57", 
            "description": "百度盘", 
            "home_url": "Module_baidupcs.asp", 
            "md5": "26a3d270863ae377921260fe7885c29c", 
            "name": "baidupcs", 
            "tar_url": "baidupcs/baidupcs.tar.gz", 
            "title": "百度盘", 
            "version": "1.9"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:58", 
            "description": "DDNSTO远程控制", 
            "home_url": "Module_ddnsto.asp", 
            "md5": "d7cdcd912b90464b9f4d4030baca2df4", 
            "name": "ddnsto", 
            "tar_url": "ddnsto/ddnsto.tar.gz", 
            "title": "DDNSTO远程控制", 
            "version": "3.0.3"
        }, 
        {
            "arch": "arm64", 
            "build_date": "2024-11-09_12:35:59", 
            "description": "腾讯云ddns", 
            "home_url": "Module_tenddns.asp", 
            "md5": "40e863afb59f57a790726955dc04dbc5", 
            "name": "tenddns", 
            "tar_url": "tenddns/tenddns.tar.gz", 
            "title": "腾讯云ddns", 
            "version": "0.0.4"
        }
    ], 
    "home_url": "https://raw.githubusercontent.com/SWRT-dev/softcenter/master", 
    "md5": "8c46b451b2f1939cf67ca70ef23bdea5", 
    "tar_url": "softcenter/softcenter.tar.gz", 
    "version": "1.5.6"
}