{
    "apps": [
        {
            "arch": "arm64",
            "build_date": "2026-05-28_09:20:14",
            "description": "内网穿透利器，谁用谁知道。",
            "home_url": "Module_frps.asp",
            "md5": "062127d291d2f9715ffe54bbfdb34142",
            "name": "frps",
            "rc_support": "",
            "tar_url": "frps/frps.tar.gz",
            "title": "frps穿透服务器",
            "version": "2.3"
        },
        {
            "arch": "arm64",
            "build_date": "2024-11-09_12:35:20",
            "description": "简便高效的异地组网、内网穿透工具",
            "home_url": "Module_vnt.asp",
            "md5": "c445caa892b8e3e6dd2dd72a1b68b2c1",
            "name": "vnt",
            "tar_url": "vnt/vnt.tar.gz",
            "title": "vnt",
            "version": "1.2"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-28_14:07:44",
            "description": "node.js",
            "home_url": "Module_node.asp",
            "md5": "dcd9bbc2e589cc08d084828c498167f9",
            "name": "node",
            "rc_support": "",
            "tar_url": "node/node.tar.gz",
            "title": "node.js",
            "version": "0.0.7"
        },
        {
            "arch": "arm64",
            "build_date": "2026-01-10_15:26:21",
            "description": "tailscale",
            "home_url": "Module_tailscale.asp",
            "md5": "8c836e1e9e5eddaad107dd23241329a8",
            "name": "tailscale",
            "tar_url": "tailscale/tailscale.tar.gz",
            "title": "tailscale",
            "version": "0.1.2"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-28_17:44:00",
            "description": "Socat 端口转发",
            "home_url": "Module_socat.asp",
            "md5": "ff584d7f9e99885140545d71ff372f20",
            "name": "socat",
            "rc_support": "",
            "tar_url": "socat/socat.tar.gz",
            "title": "Socat端口转发",
            "version": "1.3"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-28_20:19:55",
            "description": "VPN全家桶, ver 4.44 build 9807",
            "home_url": "Module_softether.asp",
            "md5": "42e2f6c79acd50ecc83fc6091ddbf33d",
            "name": "softether",
            "rc_support": "",
            "tar_url": "softether/softether.tar.gz",
            "title": "SoftEther_VPN_Server",
            "version": "2.8"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-28_21:59:06",
            "description": "局域网网速测试工具",
            "home_url": "Module_speedtest.asp",
            "md5": "42ca66f0d2bef8f0498a6fe2fedf08bd",
            "name": "speedtest",
            "rc_support": "",
            "tar_url": "speedtest/speedtest.tar.gz",
            "title": "局域网测速",
            "version": "0.0.5"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-28_08:07:48",
            "description": "FileBrowser：您的可视化路由文件管理系统",
            "home_url": "Module_filebrowser.asp",
            "md5": "135d89a9aa86c86e0b1326655fe87fad",
            "name": "filebrowser",
            "rc_support": "",
            "tar_url": "filebrowser/filebrowser.tar.gz",
            "title": "filebrowser",
            "version": "1.0.9"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-28_10:23:29",
            "description": "去广告，没烦恼",
            "home_url": "Module_koolproxy.asp",
            "md5": "c38da3986ffd9a57a40fec9ddd3fd40e",
            "name": "koolproxy",
            "rc_support": "",
            "tar_url": "koolproxy/koolproxy.tar.gz",
            "title": "koolproxy",
            "version": "3.8.5.7"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-26_15:22:23",
            "description": "阿里云盘 WebDAV 服务器",
            "home_url": "Module_aliyundrivewebdav.asp",
            "md5": "9fb76715622a6594e404ad5c7a4336a9",
            "name": "aliyundrivewebdav",
            "rc_support": "",
            "tar_url": "aliyundrivewebdav/aliyundrivewebdav.tar.gz",
            "title": "阿里云盘WebDAV",
            "version": "1.8.3"
        },
        {
            "arch": "arm64",
            "build_date": "2024-11-09_12:35:36",
            "description": "老板，来一斤虚拟内存~",
            "home_url": "Module_swap.asp",
            "md5": "43a18497312cd7eddb3e7877c593c992",
            "name": "swap",
            "tar_url": "swap/swap.tar.gz",
            "title": "虚拟内存",
            "version": "2.6"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-28_14:40:11",
            "description": "花生壳内网穿透",
            "home_url": "Module_phddns.asp",
            "md5": "214f13a49643310cef27719a03db5711",
            "name": "phddns",
            "rc_support": "",
            "tar_url": "phddns/phddns.tar.gz",
            "title": "花生壳内网穿透",
            "version": "3.0.7"
        },
        {
            "arch": "arm64",
            "build_date": "2024-11-09_12:35:37",
            "description": "分布式的虚拟以太网",
            "home_url": "Module_zerotier.asp",
            "md5": "eee415891aa13de4ffb09596a5fe79eb",
            "name": "zerotier",
            "tar_url": "zerotier/zerotier.tar.gz",
            "title": "zerotier",
            "version": "1.6"
        },
        {
            "arch": "arm64",
            "build_date": "2024-11-09_12:35:38",
            "description": "解锁网易云灰色歌曲",
            "home_url": "Module_unblockmusic.asp",
            "md5": "487f26628e509ed1ebae23e335208b41",
            "name": "unblockmusic",
            "tar_url": "unblockmusic/unblockmusic.tar.gz",
            "title": "解锁网易云灰色歌曲",
            "version": "1.2.1"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-26_21:19:00",
            "description": "Cloudflare解析自动更新IP",
            "home_url": "Module_cfddns.asp",
            "md5": "90808ce5dee0558aeed712ac78ae00de",
            "name": "cfddns",
            "rc_support": "",
            "tar_url": "cfddns/cfddns.tar.gz",
            "title": "Cloudflare DDNS",
            "version": "2.0"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-28_12:11:19",
            "description": "灵缇游戏加速插件",
            "home_url": "Module_lingti.asp",
            "md5": "65131f02aebc962f89c909857eb5928f",
            "name": "lingti",
            "rc_support": "",
            "tar_url": "lingti/lingti.tar.gz",
            "title": "灵缇游戏加速插件",
            "version": "1.0.4"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-28_12:53:00",
            "description": "lucky",
            "home_url": "Module_lucky.asp",
            "md5": "503ed6e4e11b8b1f4b0fd0998ba3278c",
            "name": "lucky",
            "rc_support": "",
            "tar_url": "lucky/lucky.tar.gz",
            "title": "lucky",
            "version": "1.4.4"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-28_09:27:31",
            "description": "kms",
            "home_url": "Module_kms.asp",
            "md5": "1a12390a0160a3f4cb36d78b96294ac3",
            "name": "kms",
            "rc_support": "",
            "tar_url": "kms/kms.tar.gz",
            "title": "系统工具",
            "version": "2.1"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-28_15:24:06",
            "description": "解决重启Bug",
            "home_url": "Module_reboothelper.asp",
            "md5": "52c921f0d72b583d50afc2f3ebd219f9",
            "name": "reboothelper",
            "rc_support": "",
            "tar_url": "reboothelper/reboothelper.tar.gz",
            "title": "重启助手",
            "version": "0.6"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-26_23:02:27",
            "description": "支持Alidns(阿里云) Dnspod(腾讯云) Cloudflare 华为云 Callback",
            "home_url": "Module_ddns.asp",
            "md5": "e32951bc7e2b4246a7ba7ff177649588",
            "name": "ddns",
            "rc_support": "",
            "tar_url": "ddns/ddns.tar.gz",
            "title": "多ddns合一",
            "version": "0.5"
        },
        {
            "arch": "arm64",
            "build_date": "2024-11-09_12:35:40",
            "description": "自己的私有云",
            "home_url": "Module_verysync.asp",
            "md5": "2a4d7a225bbb38e22814ee24096a0000",
            "name": "verysync",
            "tar_url": "verysync/verysync.tar.gz",
            "title": "微力同步",
            "version": "1.1.1"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-26_10:23:56",
            "description": "自动部署SSL证书",
            "home_url": "Module_acme.asp",
            "md5": "68f137a0f4e284254695ab0cb320c6be",
            "name": "acme",
            "rc_support": "",
            "tar_url": "acme/acme.tar.gz",
            "title": "Let's Encrypt",
            "version": "3.6"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-28_09:07:42",
            "description": "内网穿透利器，谁用谁知道。",
            "home_url": "Module_frpc.asp",
            "md5": "477de58c952d353b72bb60ec5b4937a7",
            "name": "frpc",
            "rc_support": "",
            "tar_url": "frpc/frpc.tar.gz",
            "title": "frpc穿透",
            "version": "2.7"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-26_13:02:18",
            "description": "aliddns",
            "home_url": "Module_aliddns.asp",
            "md5": "84a623a7b063448fb2f049cdc3ecb1b6",
            "name": "aliddns",
            "rc_support": "",
            "tar_url": "aliddns/aliddns.tar.gz",
            "title": "阿里DDNS",
            "version": "2.7"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-26_12:30:10",
            "description": "广告屏蔽大师 Plus 可以全面过滤各种横幅、弹窗、视频广告，同时阻止跟踪、隐私窃取及各种恶意网站",
            "home_url": "Module_adbyby.asp",
            "md5": "a5db2aedbdb9c9a324d4b47d61f50f0a",
            "name": "adbyby",
            "rc_support": "",
            "tar_url": "adbyby/adbyby.tar.gz",
            "title": "广告屏蔽大师 Plus",
            "version": "1.5"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-28_13:57:00",
            "description": "pppoe单线多拨，带宽提升神器！",
            "home_url": "Module_mdial.asp",
            "md5": "5ec1d305c351acac0e09dee62639a3a0",
            "name": "mdial",
            "rc_support": "",
            "tar_url": "mdial/mdial.tar.gz",
            "title": "单线多拨",
            "version": "1.8"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-26_17:11:00",
            "description": "linux下载利器",
            "home_url": "Module_aria2.asp",
            "md5": "51f63c7c452cd690ea784c03617d9bd3",
            "name": "aria2",
            "rc_support": "",
            "tar_url": "aria2/aria2.tar.gz",
            "title": "Aria2",
            "version": "3.3"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-26_21:48:45",
            "description": "Cloudflare Tunnel 客户端(以前称为 Argo Tunnel)",
            "home_url": "Module_cloudflared.asp",
            "md5": "cb22e8dcb17ca0e2ef8491a9b5e01431",
            "name": "cloudflared",
            "rc_support": "",
            "tar_url": "cloudflared/cloudflared.tar.gz",
            "title": "cloudflared",
            "version": "1.3"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-28_14:24:56",
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav。",
            "home_url": "Module_openlist.asp",
            "md5": "7cfa10dc30386dc6a50a0ca9debfb4d9",
            "name": "openlist",
            "rc_support": "",
            "tar_url": "openlist/openlist.tar.gz",
            "title": "OpenList文件列表",
            "version": "1.2"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-28_12:35:11",
            "description": "光猫助手: 快速设置，通过路由直接访问猫后台",
            "home_url": "Module_lookcat.asp",
            "md5": "2cae5f3a26bdf28faa78fb27e3b10dca",
            "name": "lookcat",
            "rc_support": "",
            "tar_url": "lookcat/lookcat.tar.gz",
            "title": "光猫助手",
            "version": "1.3"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-28_17:09:30",
            "description": "超强的SSH网页客户端~",
            "home_url": "Module_shellinabox.asp",
            "md5": "a13bc1da4b61e3952d421ccf2f4536c2",
            "name": "shellinabox",
            "rc_support": "",
            "tar_url": "shellinabox/shellinabox.tar.gz",
            "title": "shellinabox",
            "version": "2.6"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-28_16:25:05",
            "description": "从路由器推送状态及通知的工具",
            "home_url": "Module_serverchan.asp",
            "md5": "0f2a0fd73c328e9f6e9a5c5c051420ef",
            "name": "serverchan",
            "rc_support": "",
            "tar_url": "serverchan/serverchan.tar.gz",
            "title": "ServerChan微信推送",
            "version": "2.8"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-28_07:23:16",
            "description": "使用Dnspod的ddns服务",
            "home_url": "Module_ddnspod.asp",
            "md5": "fcd4aa41c57230466954d6e4885a9e37",
            "name": "ddnspod",
            "rc_support": "",
            "tar_url": "ddnspod/ddnspod.tar.gz",
            "title": "DDnspod",
            "version": "2.1"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-26_13:24:26",
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav，后端基于gin，前端使用react。",
            "home_url": "Module_alist.asp",
            "md5": "135d7a88f56b0fcc2b17c3832285c0f6",
            "name": "alist",
            "rc_support": "",
            "tar_url": "alist/alist.tar.gz",
            "title": "Alist文件列表",
            "version": "1.9.3"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-26_18:42:42",
            "description": "百度盘",
            "home_url": "Module_baidupcs.asp",
            "md5": "919b82cf73951bd0c9b85150538935e9",
            "name": "baidupcs",
            "rc_support": "",
            "tar_url": "baidupcs/baidupcs.tar.gz",
            "title": "百度盘",
            "version": "2.0"
        },
        {
            "arch": "arm64",
            "build_date": "2026-01-11_16:42:26",
            "description": "解锁网易云灰色歌曲",
            "home_url": "Module_unblockneteasemusic.asp",
            "md5": "46555af3662c56440fb88d75a75fb5dc",
            "name": "unblockneteasemusic",
            "tar_url": "unblockneteasemusic/unblockneteasemusic.tar.gz",
            "title": "解锁网易云灰色歌曲(nodejs版)",
            "version": "1.0.1"
        },
        {
            "arch": "arm64",
            "build_date": "2026-05-28_07:34:15",
            "description": "DDNSTO远程控制",
            "home_url": "Module_ddnsto.asp",
            "md5": "2a53b63e5af2c6e74f38fc3ec25953e2",
            "name": "ddnsto",
            "rc_support": "",
            "tar_url": "ddnsto/ddnsto.tar.gz",
            "title": "DDNSTO远程控制",
            "version": "3.0.4"
        },
        {
            "arch": "arm64",
            "build_date": "2024-11-09_12:35:59",
            "description": "腾讯云ddns",
            "home_url": "Module_tenddns.asp",
            "md5": "40e863afb59f57a790726955dc04dbc5",
            "name": "tenddns",
            "tar_url": "tenddns/tenddns.tar.gz",
            "title": "腾讯云ddns",
            "version": "0.0.4"
        }
    ],
    "home_url": "https://raw.githubusercontent.com/SWRT-dev/softcenter/master",
    "md5": "0aeae15a94090a2839e59039b49cc58c",
    "tar_url": "softcenter/softcenter.tar.gz",
    "version": "1.5.8"
}