{
    "apps": [
        {
            "arch": "armng",
            "build_date": "2026-05-28_09:20:14",
            "description": "内网穿透利器，谁用谁知道。",
            "home_url": "Module_frps.asp",
            "md5": "8c9409f9265de08beb4ee985b359d48e",
            "name": "frps",
            "rc_support": "",
            "tar_url": "frps/frps.tar.gz",
            "title": "frps穿透服务器",
            "version": "2.3"
        },
        {
            "arch": "armng",
            "build_date": "2024-11-09_12:35:20",
            "description": "简便高效的异地组网、内网穿透工具",
            "home_url": "Module_vnt.asp",
            "md5": "0c363f0e8fee98206a3eb6bbd51b63a2",
            "name": "vnt",
            "tar_url": "vnt/vnt.tar.gz",
            "title": "vnt",
            "version": "1.2"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-28_14:07:44",
            "description": "node.js",
            "home_url": "Module_node.asp",
            "md5": "07d82873989115e41ad719b8f8065017",
            "name": "node",
            "rc_support": "",
            "tar_url": "node/node.tar.gz",
            "title": "node.js",
            "version": "0.0.7"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-29_09:03:23",
            "description": "tailscale",
            "home_url": "Module_tailscale.asp",
            "md5": "3b222c53e812e546845eec05de5fbab1",
            "name": "tailscale",
            "rc_support": "",
            "tar_url": "tailscale/tailscale.tar.gz",
            "title": "tailscale",
            "version": "0.1.3"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-28_17:44:00",
            "description": "Socat 端口转发",
            "home_url": "Module_socat.asp",
            "md5": "18ad99e591b511c1261dca21eecd473d",
            "name": "socat",
            "rc_support": "",
            "tar_url": "socat/socat.tar.gz",
            "title": "Socat端口转发",
            "version": "1.3"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-28_20:19:55",
            "description": "VPN全家桶, ver 4.44 build 9807",
            "home_url": "Module_softether.asp",
            "md5": "285df4c23cb9e871004363bc3ae72f94",
            "name": "softether",
            "rc_support": "",
            "tar_url": "softether/softether.tar.gz",
            "title": "SoftEther_VPN_Server",
            "version": "2.8"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-28_21:59:05",
            "description": "局域网网速测试工具",
            "home_url": "Module_speedtest.asp",
            "md5": "d7a8bdb37e40c162b65de1c7d0b58a5a",
            "name": "speedtest",
            "rc_support": "",
            "tar_url": "speedtest/speedtest.tar.gz",
            "title": "局域网测速",
            "version": "0.0.5"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-28_08:07:47",
            "description": "FileBrowser：您的可视化路由文件管理系统",
            "home_url": "Module_filebrowser.asp",
            "md5": "551a15b87f6dc7032a643554c8429cdf",
            "name": "filebrowser",
            "rc_support": "",
            "tar_url": "filebrowser/filebrowser.tar.gz",
            "title": "filebrowser",
            "version": "1.0.9"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-28_10:23:29",
            "description": "去广告，没烦恼",
            "home_url": "Module_koolproxy.asp",
            "md5": "559650fb865da1d75207d034ecd1d852",
            "name": "koolproxy",
            "rc_support": "",
            "tar_url": "koolproxy/koolproxy.tar.gz",
            "title": "koolproxy",
            "version": "3.8.5.7"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-26_15:22:22",
            "description": "阿里云盘 WebDAV 服务器",
            "home_url": "Module_aliyundrivewebdav.asp",
            "md5": "1209afd0961778f083e8796f0d5d3416",
            "name": "aliyundrivewebdav",
            "rc_support": "",
            "tar_url": "aliyundrivewebdav/aliyundrivewebdav.tar.gz",
            "title": "阿里云盘WebDAV",
            "version": "1.8.3"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-29_08:46:54",
            "description": "老板，来一斤虚拟内存~",
            "home_url": "Module_swap.asp",
            "md5": "e8f27ca269cdba940d50b75c182f69ba",
            "name": "swap",
            "rc_support": "",
            "tar_url": "swap/swap.tar.gz",
            "title": "虚拟内存",
            "version": "2.7"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-28_14:40:11",
            "description": "花生壳内网穿透",
            "home_url": "Module_phddns.asp",
            "md5": "970af9a6e10076c31ffe612ca3019e70",
            "name": "phddns",
            "rc_support": "",
            "tar_url": "phddns/phddns.tar.gz",
            "title": "花生壳内网穿透",
            "version": "3.0.7"
        },
        {
            "arch": "armng",
            "build_date": "2024-11-09_12:35:37",
            "description": "分布式的虚拟以太网",
            "home_url": "Module_zerotier.asp",
            "md5": "269a21a9ef182ba20ff15d6fad561e82",
            "name": "zerotier",
            "tar_url": "zerotier/zerotier.tar.gz",
            "title": "zerotier",
            "version": "1.6"
        },
        {
            "arch": "armng",
            "build_date": "2024-11-09_12:35:38",
            "description": "解锁网易云灰色歌曲",
            "home_url": "Module_unblockmusic.asp",
            "md5": "a5ff0e8528fc73217785a523aa413b4b",
            "name": "unblockmusic",
            "tar_url": "unblockmusic/unblockmusic.tar.gz",
            "title": "解锁网易云灰色歌曲",
            "version": "1.2.1"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-26_21:19:00",
            "description": "Cloudflare解析自动更新IP",
            "home_url": "Module_cfddns.asp",
            "md5": "b921589e1377389efb48c4680b960232",
            "name": "cfddns",
            "rc_support": "",
            "tar_url": "cfddns/cfddns.tar.gz",
            "title": "Cloudflare DDNS",
            "version": "2.0"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-28_12:11:19",
            "description": "灵缇游戏加速插件",
            "home_url": "Module_lingti.asp",
            "md5": "bc862cd1a95f6e034188da89b666b726",
            "name": "lingti",
            "rc_support": "",
            "tar_url": "lingti/lingti.tar.gz",
            "title": "灵缇游戏加速插件",
            "version": "1.0.4"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-28_12:53:00",
            "description": "lucky",
            "home_url": "Module_lucky.asp",
            "md5": "6a36e63c49751246a90c4ea0577ea9a9",
            "name": "lucky",
            "rc_support": "",
            "tar_url": "lucky/lucky.tar.gz",
            "title": "lucky",
            "version": "1.4.4"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-28_09:27:31",
            "description": "kms",
            "home_url": "Module_kms.asp",
            "md5": "f78640fa15b941d2febc8e3ebe60e2d9",
            "name": "kms",
            "rc_support": "",
            "tar_url": "kms/kms.tar.gz",
            "title": "系统工具",
            "version": "2.1"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-28_15:24:06",
            "description": "解决重启Bug",
            "home_url": "Module_reboothelper.asp",
            "md5": "f279ac45a1e660d75b130ee773736d59",
            "name": "reboothelper",
            "rc_support": "",
            "tar_url": "reboothelper/reboothelper.tar.gz",
            "title": "重启助手",
            "version": "0.6"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-26_23:02:27",
            "description": "支持Alidns(阿里云) Dnspod(腾讯云) Cloudflare 华为云 Callback",
            "home_url": "Module_ddns.asp",
            "md5": "a6048de789592f2a8c2e0be3a2014237",
            "name": "ddns",
            "rc_support": "",
            "tar_url": "ddns/ddns.tar.gz",
            "title": "多ddns合一",
            "version": "0.5"
        },
        {
            "arch": "armng",
            "build_date": "2024-11-09_12:35:40",
            "description": "自己的私有云",
            "home_url": "Module_verysync.asp",
            "md5": "080a96fbedab4ef7b77ca91170e2a77d",
            "name": "verysync",
            "tar_url": "verysync/verysync.tar.gz",
            "title": "微力同步",
            "version": "1.1.1"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-26_10:23:56",
            "description": "自动部署SSL证书",
            "home_url": "Module_acme.asp",
            "md5": "36c8bc85ec0148bacfcae9015bef88cb",
            "name": "acme",
            "rc_support": "",
            "tar_url": "acme/acme.tar.gz",
            "title": "Let's Encrypt",
            "version": "3.6"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-28_09:07:42",
            "description": "内网穿透利器，谁用谁知道。",
            "home_url": "Module_frpc.asp",
            "md5": "e9c4b42a776eaf6ece1c649ef6e7eefb",
            "name": "frpc",
            "rc_support": "",
            "tar_url": "frpc/frpc.tar.gz",
            "title": "frpc穿透",
            "version": "2.7"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-26_13:02:18",
            "description": "aliddns",
            "home_url": "Module_aliddns.asp",
            "md5": "0855c4b6e46a9733a47aab2687dd6925",
            "name": "aliddns",
            "rc_support": "",
            "tar_url": "aliddns/aliddns.tar.gz",
            "title": "阿里DDNS",
            "version": "2.7"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-26_12:30:10",
            "description": "广告屏蔽大师 Plus 可以全面过滤各种横幅、弹窗、视频广告，同时阻止跟踪、隐私窃取及各种恶意网站",
            "home_url": "Module_adbyby.asp",
            "md5": "b7e41df998ae0495604f0b2c19fc2781",
            "name": "adbyby",
            "rc_support": "",
            "tar_url": "adbyby/adbyby.tar.gz",
            "title": "广告屏蔽大师 Plus",
            "version": "1.5"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-28_13:57:00",
            "description": "pppoe单线多拨，带宽提升神器！",
            "home_url": "Module_mdial.asp",
            "md5": "0ff3b69aa9c7e74a43e7abb5884f1bfb",
            "name": "mdial",
            "rc_support": "",
            "tar_url": "mdial/mdial.tar.gz",
            "title": "单线多拨",
            "version": "1.8"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-26_17:11:00",
            "description": "linux下载利器",
            "home_url": "Module_aria2.asp",
            "md5": "f0dace1e185b5cfb74e7ce33290b9267",
            "name": "aria2",
            "rc_support": "",
            "tar_url": "aria2/aria2.tar.gz",
            "title": "Aria2",
            "version": "3.3"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-26_21:48:45",
            "description": "Cloudflare Tunnel 客户端(以前称为 Argo Tunnel)",
            "home_url": "Module_cloudflared.asp",
            "md5": "7aedc198ded61d6131c4cf485b0c071c",
            "name": "cloudflared",
            "rc_support": "",
            "tar_url": "cloudflared/cloudflared.tar.gz",
            "title": "cloudflared",
            "version": "1.3"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-28_14:24:55",
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav。",
            "home_url": "Module_openlist.asp",
            "md5": "beb3dbbe553671a2f78796adeb42efb0",
            "name": "openlist",
            "rc_support": "",
            "tar_url": "openlist/openlist.tar.gz",
            "title": "OpenList文件列表",
            "version": "1.2"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-28_12:35:11",
            "description": "光猫助手: 快速设置，通过路由直接访问猫后台",
            "home_url": "Module_lookcat.asp",
            "md5": "c78aa369db68b746dba92cd3882a63ef",
            "name": "lookcat",
            "rc_support": "",
            "tar_url": "lookcat/lookcat.tar.gz",
            "title": "光猫助手",
            "version": "1.3"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-28_17:09:30",
            "description": "超强的SSH网页客户端~",
            "home_url": "Module_shellinabox.asp",
            "md5": "7bf828ed3263a86234924403f3a3c43f",
            "name": "shellinabox",
            "rc_support": "",
            "tar_url": "shellinabox/shellinabox.tar.gz",
            "title": "shellinabox",
            "version": "2.6"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-28_16:25:05",
            "description": "从路由器推送状态及通知的工具",
            "home_url": "Module_serverchan.asp",
            "md5": "4dff760b0b48609af84d026a0a43dd17",
            "name": "serverchan",
            "rc_support": "",
            "tar_url": "serverchan/serverchan.tar.gz",
            "title": "ServerChan微信推送",
            "version": "2.8"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-28_07:23:16",
            "description": "使用Dnspod的ddns服务",
            "home_url": "Module_ddnspod.asp",
            "md5": "f18ae30832f3b8bf0de40f1e6c74da8f",
            "name": "ddnspod",
            "rc_support": "",
            "tar_url": "ddnspod/ddnspod.tar.gz",
            "title": "DDnspod",
            "version": "2.1"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-26_13:24:25",
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav，后端基于gin，前端使用react。",
            "home_url": "Module_alist.asp",
            "md5": "66bfa3b79e96de0e0c4ce684b104b973",
            "name": "alist",
            "rc_support": "",
            "tar_url": "alist/alist.tar.gz",
            "title": "Alist文件列表",
            "version": "1.9.3"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-26_18:42:41",
            "description": "百度盘",
            "home_url": "Module_baidupcs.asp",
            "md5": "9d69b8f152c5e12ee52d956a2f51747d",
            "name": "baidupcs",
            "rc_support": "",
            "tar_url": "baidupcs/baidupcs.tar.gz",
            "title": "百度盘",
            "version": "2.0"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-28_07:34:15",
            "description": "DDNSTO远程控制",
            "home_url": "Module_ddnsto.asp",
            "md5": "13ee0f30d3b27f963c799a97456f9432",
            "name": "ddnsto",
            "rc_support": "",
            "tar_url": "ddnsto/ddnsto.tar.gz",
            "title": "DDNSTO远程控制",
            "version": "3.0.4"
        },
        {
            "arch": "armng",
            "build_date": "2026-05-29_09:10:01",
            "description": "腾讯云ddns",
            "home_url": "Module_tenddns.asp",
            "md5": "df13ba5c9689f0afffc0a796f3205d39",
            "name": "tenddns",
            "rc_support": "",
            "tar_url": "tenddns/tenddns.tar.gz",
            "title": "腾讯云ddns",
            "version": "0.0.5"
        }
    ],
    "home_url": "https://raw.githubusercontent.com/SWRT-dev/softcenter/master",
    "md5": "84d670a9bc8de1d5d835982a4215b31b",
    "tar_url": "softcenter/softcenter.tar.gz",
    "version": "1.5.8"
}