{
    "apps": [
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:11:48", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frps.asp", 
            "md5": "03f86900a54f99a3e76fa4aa9d53019b", 
            "name": "frps", 
            "tar_url": "armng/frps/frps.tar.gz", 
            "title": "frps穿透服务器", 
            "version": "2.1"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:11:49", 
            "description": "简便高效的异地组网、内网穿透工具", 
            "home_url": "Module_vnt.asp", 
            "md5": "e3f052282fa07275110b18f4304d5987", 
            "name": "vnt", 
            "tar_url": "armng/vnt/vnt.tar.gz", 
            "title": "vnt", 
            "version": "1.2"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:11:49", 
            "description": "node.js", 
            "home_url": "Module_node.asp", 
            "md5": "7c17f92d55ef9c28ae8a7f2a3ec3040c", 
            "name": "node", 
            "tar_url": "armng/node/node.tar.gz", 
            "title": "node.js", 
            "version": "0.0.6"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:11:52", 
            "description": "tailscale", 
            "home_url": "Module_tailscale.asp", 
            "md5": "e6c449fffde8561d093061e69b7f0547", 
            "name": "tailscale", 
            "tar_url": "armng/tailscale/tailscale.tar.gz", 
            "title": "tailscale", 
            "version": "0.0.8"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:11:55", 
            "description": "Socat 端口转发", 
            "home_url": "Module_socat.asp", 
            "md5": "77b03a976ab6fb131119452af552d01a", 
            "name": "socat", 
            "tar_url": "armng/socat/socat.tar.gz", 
            "title": "Socat端口转发", 
            "version": "1.1"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:11:55", 
            "description": "VPN全家桶, ver 4.30 build 9700", 
            "home_url": "", 
            "md5": "a2c231f0847211ee0f47c8acc1c488dd", 
            "name": "softether", 
            "tar_url": "armng/softether/softether.tar.gz", 
            "title": "SoftEther_VPN_Server", 
            "version": "2.4"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:11:57", 
            "description": "局域网网速测试工具", 
            "home_url": "Module_speedtest.asp", 
            "md5": "5b1370e1859383da2a3b8f0f38cd4b60", 
            "name": "speedtest", 
            "tar_url": "armng/speedtest/speedtest.tar.gz", 
            "title": "局域网测速", 
            "version": "0.0.4"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:11:58", 
            "description": "FileBrowser：您的可视化路由文件管理系统", 
            "home_url": "Module_filebrowser.asp", 
            "md5": "04200b49f904bf811fe1cc006a169d34", 
            "name": "filebrowser", 
            "tar_url": "armng/filebrowser/filebrowser.tar.gz", 
            "title": "filebrowser", 
            "version": "1.0.7"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:11:59", 
            "description": "去广告，没烦恼", 
            "home_url": "Module_koolproxy.asp", 
            "md5": "2e55d76318153aa305e1572dfcf4439e", 
            "name": "koolproxy", 
            "tar_url": "armng/koolproxy/koolproxy.tar.gz", 
            "title": "koolproxy", 
            "version": "3.8.5.6"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:11:59", 
            "description": "阿里云盘 WebDAV 服务器", 
            "home_url": "Module_aliyundrivewebdav.asp", 
            "md5": "35a03d1975fc12e45c88b90688474b36", 
            "name": "aliyundrivewebdav", 
            "tar_url": "armng/aliyundrivewebdav/aliyundrivewebdav.tar.gz", 
            "title": "阿里云盘WebDAV", 
            "version": "1.8.2"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:00", 
            "description": "老板，来一斤虚拟内存~", 
            "home_url": "Module_swap.asp", 
            "md5": "c8e33a6564b6af96d218ec7a24012ecb", 
            "name": "swap", 
            "tar_url": "armng/swap/swap.tar.gz", 
            "title": "虚拟内存", 
            "version": "2.6"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:00", 
            "description": "花生壳内网穿透", 
            "home_url": "Module_phddns.asp", 
            "md5": "7c6de3cedca07eef6b3447b984ef4ef2", 
            "name": "phddns", 
            "tar_url": "armng/phddns/phddns.tar.gz", 
            "title": "花生壳内网穿透", 
            "version": "3.0.6"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:01", 
            "description": "分布式的虚拟以太网", 
            "home_url": "Module_zerotier.asp", 
            "md5": "149f01db529c3a9d98fd04d1f88bc0e6", 
            "name": "zerotier", 
            "tar_url": "armng/zerotier/zerotier.tar.gz", 
            "title": "zerotier", 
            "version": "1.6"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:02", 
            "description": "解锁网易云灰色歌曲", 
            "home_url": "Module_unblockmusic.asp", 
            "md5": "61387d347bf91afeac26357791e59d26", 
            "name": "unblockmusic", 
            "tar_url": "armng/unblockmusic/unblockmusic.tar.gz", 
            "title": "解锁网易云灰色歌曲", 
            "version": "1.2.1"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:02", 
            "description": "Cloudflare解析自动更新IP", 
            "home_url": "Module_cfddns.asp", 
            "md5": "1bc820f329f6059bffe4960d78d10e42", 
            "name": "cfddns", 
            "tar_url": "armng/cfddns/cfddns.tar.gz", 
            "title": "Cloudflare DDNS", 
            "version": "1.9"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:02", 
            "description": "灵缇游戏加速插件", 
            "home_url": "Module_lingti.asp", 
            "md5": "9d5af8ba1af91f762a2d5bdc95201f40", 
            "name": "lingti", 
            "tar_url": "armng/lingti/lingti.tar.gz", 
            "title": "灵缇游戏加速插件", 
            "version": "1.0.3"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:02", 
            "description": "kms", 
            "home_url": "Module_kms.asp", 
            "md5": "3754b8f469ed031134150ceaea35b575", 
            "name": "kms", 
            "tar_url": "armng/kms/kms.tar.gz", 
            "title": "系统工具", 
            "version": "2.0"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:03", 
            "description": "解决重启Bug", 
            "home_url": "Module_reboothelper.asp", 
            "md5": "c60830e443f32f210e533478528fc9ee", 
            "name": "reboothelper", 
            "tar_url": "armng/reboothelper/reboothelper.tar.gz", 
            "title": "重启助手", 
            "version": "0.5"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:03", 
            "description": "支持Alidns(阿里云) Dnspod(腾讯云) Cloudflare 华为云 Callback", 
            "home_url": "Module_ddns.asp", 
            "md5": "b8dec1d2e171975ef34f8b475b9423d1", 
            "name": "ddns", 
            "tar_url": "armng/ddns/ddns.tar.gz", 
            "title": "多ddns合一", 
            "version": "0.3"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:03", 
            "description": "自己的私有云", 
            "home_url": "Module_verysync.asp", 
            "md5": "c120f5b9349a39aa7270ced419daa832", 
            "name": "verysync", 
            "tar_url": "armng/verysync/verysync.tar.gz", 
            "title": "微力同步", 
            "version": "1.1.1"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:03", 
            "description": "自动部署SSL证书", 
            "home_url": "Module_acme.asp", 
            "md5": "70fb48bdeec469a141a75a84a27e35b1", 
            "name": "acme", 
            "tar_url": "armng/acme/acme.tar.gz", 
            "title": "Let's Encrypt", 
            "version": "3.5"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:04", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frpc.asp", 
            "md5": "04a059cad4b0ae4690112b7368ad5d38", 
            "name": "frpc", 
            "tar_url": "armng/frpc/frpc.tar.gz", 
            "title": "frpc穿透", 
            "version": "2.5"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:04", 
            "description": "aliddns", 
            "home_url": "Module_aliddns.asp", 
            "md5": "68dd631a0ecc09ff4d66b94377a42ad8", 
            "name": "aliddns", 
            "tar_url": "armng/aliddns/aliddns.tar.gz", 
            "title": "阿里DDNS", 
            "version": "2.6"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:05", 
            "description": "广告屏蔽大师 Plus 可以全面过滤各种横幅、弹窗、视频广告，同时阻止跟踪、隐私窃取及各种恶意网站", 
            "home_url": "Module_adbyby.asp", 
            "md5": "74f4c4aabb37ee7ecca8d19e552eb569", 
            "name": "adbyby", 
            "tar_url": "armng/adbyby/adbyby.tar.gz", 
            "title": "广告屏蔽大师 Plus", 
            "version": "1.4"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:05", 
            "description": "pppoe单线多拨，带宽提升神器！", 
            "home_url": "Module_mdial.asp", 
            "md5": "e403f1cc42c277ddc901c0fb587616a8", 
            "name": "mdial", 
            "tar_url": "armng/mdial/mdial.tar.gz", 
            "title": "单线多拨", 
            "version": "1.7"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:05", 
            "description": "linux下载利器", 
            "home_url": "Module_aria2.asp", 
            "md5": "36a55685aef4fcb629bd68ff97491c68", 
            "name": "aria2", 
            "tar_url": "armng/aria2/aria2.tar.gz", 
            "title": "Aria2", 
            "version": "3.2"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:06", 
            "description": "Cloudflare Tunnel 客户端(以前称为 Argo Tunnel)", 
            "home_url": "Module_cloudflared.asp", 
            "md5": "b3ac071fd0e2bb46ae300049bc43a479", 
            "name": "cloudflared", 
            "tar_url": "armng/cloudflared/cloudflared.tar.gz", 
            "title": "cloudflared", 
            "version": "1.1"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:07", 
            "description": "这是一只自动帮你签到的dog", 
            "home_url": "Module_qiandao.asp", 
            "md5": "ed48ec2b5e6d438f1739e0bae84fb6ac", 
            "name": "qiandao", 
            "tar_url": "armng/qiandao/qiandao.tar.gz", 
            "title": "签到dog", 
            "version": "1.8"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:08", 
            "description": "光猫助手: 快速设置，通过路由直接访问猫后台", 
            "home_url": "Module_lookcat.asp", 
            "md5": "51f3cf9c81a62da990b53e84e505b30d", 
            "name": "lookcat", 
            "tar_url": "armng/lookcat/lookcat.tar.gz", 
            "title": "光猫助手", 
            "version": "1.2"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:08", 
            "description": "超强的SSH网页客户端~", 
            "home_url": "Module_shellinabox.asp", 
            "md5": "9953b2b14e02950918c4b5e280adf0ed", 
            "name": "shellinabox", 
            "tar_url": "armng/shellinabox/shellinabox.tar.gz", 
            "title": "shellinabox", 
            "version": "2.5"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:08", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_serverchan.asp", 
            "md5": "3a168704aa9cbd37fcc9058b4f8ba16e", 
            "name": "serverchan", 
            "tar_url": "armng/serverchan/serverchan.tar.gz", 
            "title": "ServerChan微信推送", 
            "version": "2.7"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:08", 
            "description": "使用Dnspod的ddns服务", 
            "home_url": "Module_ddnspod.asp", 
            "md5": "a15722e269d790590faa128f4e14c680", 
            "name": "ddnspod", 
            "tar_url": "armng/ddnspod/ddnspod.tar.gz", 
            "title": "DDnspod", 
            "version": "2.0"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:10", 
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav，后端基于gin，前端使用react。", 
            "home_url": "Module_alist.asp", 
            "md5": "3a7a1edebae0396a92ca863b23c6a5b5", 
            "name": "alist", 
            "tar_url": "armng/alist/alist.tar.gz", 
            "title": "Alist文件列表", 
            "version": "1.9.2"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:14", 
            "description": "百度盘", 
            "home_url": "Module_baidupcs.asp", 
            "md5": "f731c813149923fc81dbcaef1a013ddb", 
            "name": "baidupcs", 
            "tar_url": "armng/baidupcs/baidupcs.tar.gz", 
            "title": "百度盘", 
            "version": "1.9"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:16", 
            "description": "DDNSTO远程控制", 
            "home_url": "Module_ddnsto.asp", 
            "md5": "361c065db01575322f8e4a4702cd6cba", 
            "name": "ddnsto", 
            "tar_url": "armng/ddnsto/ddnsto.tar.gz", 
            "title": "DDNSTO远程控制", 
            "version": "3.0.3"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-10-31_14:12:16", 
            "description": "腾讯云ddns", 
            "home_url": "Module_tenddns.asp", 
            "md5": "5665184e76e3fbf536b05a294a9c1ec0", 
            "name": "tenddns", 
            "tar_url": "armng/tenddns/tenddns.tar.gz", 
            "title": "腾讯云ddns", 
            "version": "0.0.4"
        }
    ], 
    "home_url": "https://raw.githubusercontent.com/SWRT-dev/softcenter/master", 
    "md5": "fa64949838b599aa25605d33e3fc4b0c", 
    "tar_url": "armng/softcenter/softcenter.tar.gz", 
    "version": "1.5.4"
}