{
    "apps": [
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:19", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frps.asp", 
            "md5": "a63b73d9d5442d81781d4dbca59515b1", 
            "name": "frps", 
            "tar_url": "frps/frps.tar.gz", 
            "title": "frps穿透服务器", 
            "version": "2.1"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:20", 
            "description": "简便高效的异地组网、内网穿透工具", 
            "home_url": "Module_vnt.asp", 
            "md5": "0c363f0e8fee98206a3eb6bbd51b63a2", 
            "name": "vnt", 
            "tar_url": "vnt/vnt.tar.gz", 
            "title": "vnt", 
            "version": "1.2"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:21", 
            "description": "node.js", 
            "home_url": "Module_node.asp", 
            "md5": "5c4b4ece845e4d58eb2e5443b3d412cc", 
            "name": "node", 
            "tar_url": "node/node.tar.gz", 
            "title": "node.js", 
            "version": "0.0.6"
        }, 
        {
            "arch": "armng", 
            "build_date": "2025-03-08_15:54:14", 
            "description": "tailscale", 
            "home_url": "Module_tailscale.asp", 
            "md5": "85a2ebbec47a2a5592b306938fded814", 
            "name": "tailscale", 
            "tar_url": "tailscale/tailscale.tar.gz", 
            "title": "tailscale", 
            "version": "0.0.9"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:29", 
            "description": "Socat 端口转发", 
            "home_url": "Module_socat.asp", 
            "md5": "bd492d9f42ddd9b7bcc6c7e97f36ff88", 
            "name": "socat", 
            "tar_url": "socat/socat.tar.gz", 
            "title": "Socat端口转发", 
            "version": "1.1"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:30", 
            "description": "VPN全家桶, ver 4.30 build 9700", 
            "home_url": "", 
            "md5": "08492a2163619845fe6bb5c11d4c8e7f", 
            "name": "softether", 
            "tar_url": "softether/softether.tar.gz", 
            "title": "SoftEther_VPN_Server", 
            "version": "2.4"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:32", 
            "description": "局域网网速测试工具", 
            "home_url": "Module_speedtest.asp", 
            "md5": "61067750d50422119a7976abab0bdad9", 
            "name": "speedtest", 
            "tar_url": "speedtest/speedtest.tar.gz", 
            "title": "局域网测速", 
            "version": "0.0.4"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:33", 
            "description": "FileBrowser：您的可视化路由文件管理系统", 
            "home_url": "Module_filebrowser.asp", 
            "md5": "51e797b3331b7c2af84c3f51097d66c5", 
            "name": "filebrowser", 
            "tar_url": "filebrowser/filebrowser.tar.gz", 
            "title": "filebrowser", 
            "version": "1.0.7"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:34", 
            "description": "去广告，没烦恼", 
            "home_url": "Module_koolproxy.asp", 
            "md5": "2be61cb8d3d304cba8c6c10b17eb6836", 
            "name": "koolproxy", 
            "tar_url": "koolproxy/koolproxy.tar.gz", 
            "title": "koolproxy", 
            "version": "3.8.5.6"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:35", 
            "description": "阿里云盘 WebDAV 服务器", 
            "home_url": "Module_aliyundrivewebdav.asp", 
            "md5": "5248759052f6b8107b9c8c0e2564be28", 
            "name": "aliyundrivewebdav", 
            "tar_url": "aliyundrivewebdav/aliyundrivewebdav.tar.gz", 
            "title": "阿里云盘WebDAV", 
            "version": "1.8.2"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:36", 
            "description": "老板，来一斤虚拟内存~", 
            "home_url": "Module_swap.asp", 
            "md5": "fe4c8ac53c112a99f28803b06093b620", 
            "name": "swap", 
            "tar_url": "swap/swap.tar.gz", 
            "title": "虚拟内存", 
            "version": "2.6"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:36", 
            "description": "花生壳内网穿透", 
            "home_url": "Module_phddns.asp", 
            "md5": "9f4a959970fb26e39994a53c5a72121c", 
            "name": "phddns", 
            "tar_url": "phddns/phddns.tar.gz", 
            "title": "花生壳内网穿透", 
            "version": "3.0.6"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:37", 
            "description": "分布式的虚拟以太网", 
            "home_url": "Module_zerotier.asp", 
            "md5": "269a21a9ef182ba20ff15d6fad561e82", 
            "name": "zerotier", 
            "tar_url": "zerotier/zerotier.tar.gz", 
            "title": "zerotier", 
            "version": "1.6"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:38", 
            "description": "解锁网易云灰色歌曲", 
            "home_url": "Module_unblockmusic.asp", 
            "md5": "a5ff0e8528fc73217785a523aa413b4b", 
            "name": "unblockmusic", 
            "tar_url": "unblockmusic/unblockmusic.tar.gz", 
            "title": "解锁网易云灰色歌曲", 
            "version": "1.2.1"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:38", 
            "description": "Cloudflare解析自动更新IP", 
            "home_url": "Module_cfddns.asp", 
            "md5": "143ada260fb0e1039980cb05aa8fbf74", 
            "name": "cfddns", 
            "tar_url": "cfddns/cfddns.tar.gz", 
            "title": "Cloudflare DDNS", 
            "version": "1.9"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:39", 
            "description": "灵缇游戏加速插件", 
            "home_url": "Module_lingti.asp", 
            "md5": "c74297f536faa90126590246f7a3f6b9", 
            "name": "lingti", 
            "tar_url": "lingti/lingti.tar.gz", 
            "title": "灵缇游戏加速插件", 
            "version": "1.0.3"
        }, 
        {
            "arch": "armng", 
            "build_date": "2025-03-23_14:29:52", 
            "description": "lucky", 
            "home_url": "Module_lucky.asp", 
            "md5": "008bfd3a7b351cfbc49c815994c70b52", 
            "name": "lucky", 
            "tar_url": "lucky/lucky.tar.gz", 
            "title": "lucky", 
            "version": "1.4.3"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:39", 
            "description": "kms", 
            "home_url": "Module_kms.asp", 
            "md5": "4413b4f992bccbe579ded8050cb8c5d0", 
            "name": "kms", 
            "tar_url": "kms/kms.tar.gz", 
            "title": "系统工具", 
            "version": "2.0"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:40", 
            "description": "解决重启Bug", 
            "home_url": "Module_reboothelper.asp", 
            "md5": "af8ef089974a889173720341887e076d", 
            "name": "reboothelper", 
            "tar_url": "reboothelper/reboothelper.tar.gz", 
            "title": "重启助手", 
            "version": "0.5"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:40", 
            "description": "支持Alidns(阿里云) Dnspod(腾讯云) Cloudflare 华为云 Callback", 
            "home_url": "Module_ddns.asp", 
            "md5": "a3002d3aa37444ca8562126c4c9c6629", 
            "name": "ddns", 
            "tar_url": "ddns/ddns.tar.gz", 
            "title": "多ddns合一", 
            "version": "0.3"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:40", 
            "description": "自己的私有云", 
            "home_url": "Module_verysync.asp", 
            "md5": "080a96fbedab4ef7b77ca91170e2a77d", 
            "name": "verysync", 
            "tar_url": "verysync/verysync.tar.gz", 
            "title": "微力同步", 
            "version": "1.1.1"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:41", 
            "description": "自动部署SSL证书", 
            "home_url": "Module_acme.asp", 
            "md5": "024f57ac3f8600bfd1db8f869d73fded", 
            "name": "acme", 
            "tar_url": "acme/acme.tar.gz", 
            "title": "Let's Encrypt", 
            "version": "3.5"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:41", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frpc.asp", 
            "md5": "a533c5b27513ed6a73c6525e700c537d", 
            "name": "frpc", 
            "tar_url": "frpc/frpc.tar.gz", 
            "title": "frpc穿透", 
            "version": "2.5"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:42", 
            "description": "aliddns", 
            "home_url": "Module_aliddns.asp", 
            "md5": "3cd6074dc15c03757f3553e9570309ae", 
            "name": "aliddns", 
            "tar_url": "aliddns/aliddns.tar.gz", 
            "title": "阿里DDNS", 
            "version": "2.6"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:42", 
            "description": "广告屏蔽大师 Plus 可以全面过滤各种横幅、弹窗、视频广告，同时阻止跟踪、隐私窃取及各种恶意网站", 
            "home_url": "Module_adbyby.asp", 
            "md5": "ec3b0ec5078afec0cd6cf756fa582a7a", 
            "name": "adbyby", 
            "tar_url": "adbyby/adbyby.tar.gz", 
            "title": "广告屏蔽大师 Plus", 
            "version": "1.4"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:43", 
            "description": "pppoe单线多拨，带宽提升神器！", 
            "home_url": "Module_mdial.asp", 
            "md5": "2c0a2023bcc86d6bccec57eaf524ba20", 
            "name": "mdial", 
            "tar_url": "mdial/mdial.tar.gz", 
            "title": "单线多拨", 
            "version": "1.7"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:43", 
            "description": "linux下载利器", 
            "home_url": "Module_aria2.asp", 
            "md5": "709121df960b6d230fcefec8aa8a8149", 
            "name": "aria2", 
            "tar_url": "aria2/aria2.tar.gz", 
            "title": "Aria2", 
            "version": "3.2"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-12-04_18:20:20", 
            "description": "Cloudflare Tunnel 客户端(以前称为 Argo Tunnel)", 
            "home_url": "Module_cloudflared.asp", 
            "md5": "622007f325be6b37578a272a51d656c3", 
            "name": "cloudflared", 
            "tar_url": "cloudflared/cloudflared.tar.gz", 
            "title": "cloudflared", 
            "version": "1.2"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:46", 
            "description": "这是一只自动帮你签到的dog", 
            "home_url": "Module_qiandao.asp", 
            "md5": "c021d2548ed72a61732b27c14f156a20", 
            "name": "qiandao", 
            "tar_url": "qiandao/qiandao.tar.gz", 
            "title": "签到dog", 
            "version": "1.8"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:47", 
            "description": "光猫助手: 快速设置，通过路由直接访问猫后台", 
            "home_url": "Module_lookcat.asp", 
            "md5": "954c9ca0282ef02d84b9580589d13cc2", 
            "name": "lookcat", 
            "tar_url": "lookcat/lookcat.tar.gz", 
            "title": "光猫助手", 
            "version": "1.2"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:47", 
            "description": "超强的SSH网页客户端~", 
            "home_url": "Module_shellinabox.asp", 
            "md5": "5e7257d63c7baebbd19dbee94a1aa0e2", 
            "name": "shellinabox", 
            "tar_url": "shellinabox/shellinabox.tar.gz", 
            "title": "shellinabox", 
            "version": "2.5"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:47", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_serverchan.asp", 
            "md5": "0fc3f49002acadb4144e08f8f900acc6", 
            "name": "serverchan", 
            "tar_url": "serverchan/serverchan.tar.gz", 
            "title": "ServerChan微信推送", 
            "version": "2.7"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:48", 
            "description": "使用Dnspod的ddns服务", 
            "home_url": "Module_ddnspod.asp", 
            "md5": "9588f6f9064e01d656a73dae5f1e08a1", 
            "name": "ddnspod", 
            "tar_url": "ddnspod/ddnspod.tar.gz", 
            "title": "DDnspod", 
            "version": "2.0"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:50", 
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav，后端基于gin，前端使用react。", 
            "home_url": "Module_alist.asp", 
            "md5": "6313db9989d537fd8aa7137467a3938f", 
            "name": "alist", 
            "tar_url": "alist/alist.tar.gz", 
            "title": "Alist文件列表", 
            "version": "1.9.2"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:56", 
            "description": "百度盘", 
            "home_url": "Module_baidupcs.asp", 
            "md5": "84de8957f2c7539133e0bcf78ca262b3", 
            "name": "baidupcs", 
            "tar_url": "baidupcs/baidupcs.tar.gz", 
            "title": "百度盘", 
            "version": "1.9"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:58", 
            "description": "DDNSTO远程控制", 
            "home_url": "Module_ddnsto.asp", 
            "md5": "7930ae1e6eb501927838b22dc62f9faa", 
            "name": "ddnsto", 
            "tar_url": "ddnsto/ddnsto.tar.gz", 
            "title": "DDNSTO远程控制", 
            "version": "3.0.3"
        }, 
        {
            "arch": "armng", 
            "build_date": "2024-11-09_12:35:59", 
            "description": "腾讯云ddns", 
            "home_url": "Module_tenddns.asp", 
            "md5": "908e1c43db2fac4cc5ab01b0b9a89b59", 
            "name": "tenddns", 
            "tar_url": "tenddns/tenddns.tar.gz", 
            "title": "腾讯云ddns", 
            "version": "0.0.4"
        }
    ], 
    "home_url": "https://raw.githubusercontent.com/SWRT-dev/softcenter/master", 
    "md5": "0e26e96d7081b11964a714affae297fd", 
    "tar_url": "softcenter/softcenter.tar.gz", 
    "version": "1.5.5"
}