{
    "apps": [
        {
            "arch": "mipsle", 
            "build_date": "2025-09-05_14:32:45", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frps.asp", 
            "md5": "adb86f48f316a23340570dd6bfe5ba89", 
            "name": "frps", 
            "tar_url": "frps/frps.tar.gz", 
            "title": "frps穿透服务器", 
            "version": "2.2"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:20", 
            "description": "简便高效的异地组网、内网穿透工具", 
            "home_url": "Module_vnt.asp", 
            "md5": "58d0b93d1a6568ca80ca73a9fce565f5", 
            "name": "vnt", 
            "tar_url": "vnt/vnt.tar.gz", 
            "title": "vnt", 
            "version": "1.2"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:22", 
            "description": "node.js", 
            "home_url": "Module_node.asp", 
            "md5": "11a0686123203bae2b10a57df24d7f3f", 
            "name": "node", 
            "tar_url": "node/node.tar.gz", 
            "title": "node.js", 
            "version": "0.0.6"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2025-03-08_15:54:17", 
            "description": "tailscale", 
            "home_url": "Module_tailscale.asp", 
            "md5": "25de9ef67acff5382cbf830912c9421a", 
            "name": "tailscale", 
            "tar_url": "tailscale/tailscale.tar.gz", 
            "title": "tailscale", 
            "version": "0.0.9"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2025-09-04_22:50:38", 
            "description": "Socat 端口转发", 
            "home_url": "Module_socat.asp", 
            "md5": "2f47fd58cfb54dca49b65b53a9e935e1", 
            "name": "socat", 
            "tar_url": "socat/socat.tar.gz", 
            "title": "Socat端口转发", 
            "version": "1.2"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2025-09-04_22:17:24", 
            "description": "VPN全家桶, ver 4.44 build 9807", 
            "home_url": "", 
            "md5": "16c9d7845995029092ffcfa1f17e32ab", 
            "name": "softether", 
            "tar_url": "softether/softether.tar.gz", 
            "title": "SoftEther_VPN_Server", 
            "version": "2.5"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:32", 
            "description": "局域网网速测试工具", 
            "home_url": "Module_speedtest.asp", 
            "md5": "eb30a643c9c1f53b5c756ae914f56d22", 
            "name": "speedtest", 
            "tar_url": "speedtest/speedtest.tar.gz", 
            "title": "局域网测速", 
            "version": "0.0.4"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2025-09-06_12:18:23", 
            "description": "FileBrowser：您的可视化路由文件管理系统", 
            "home_url": "Module_filebrowser.asp", 
            "md5": "92f948635d9649f176f72bd42924a85c", 
            "name": "filebrowser", 
            "tar_url": "filebrowser/filebrowser.tar.gz", 
            "title": "filebrowser", 
            "version": "1.0.8"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:34", 
            "description": "去广告，没烦恼", 
            "home_url": "Module_koolproxy.asp", 
            "md5": "ecd94b306b81fab40cc62d070f616eb4", 
            "name": "koolproxy", 
            "tar_url": "koolproxy/koolproxy.tar.gz", 
            "title": "koolproxy", 
            "version": "3.8.5.6"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:36", 
            "description": "阿里云盘 WebDAV 服务器", 
            "home_url": "Module_aliyundrivewebdav.asp", 
            "md5": "07603964f16447cc01272f94edbe059f", 
            "name": "aliyundrivewebdav", 
            "tar_url": "aliyundrivewebdav/aliyundrivewebdav.tar.gz", 
            "title": "阿里云盘WebDAV", 
            "version": "1.8.2"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:36", 
            "description": "老板，来一斤虚拟内存~", 
            "home_url": "Module_swap.asp", 
            "md5": "e0e9d8147bb47d6421d6a82221286444", 
            "name": "swap", 
            "tar_url": "swap/swap.tar.gz", 
            "title": "虚拟内存", 
            "version": "2.6"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:36", 
            "description": "花生壳内网穿透", 
            "home_url": "Module_phddns.asp", 
            "md5": "6e76bdda6a6a562f20fdc5090495a16d", 
            "name": "phddns", 
            "tar_url": "phddns/phddns.tar.gz", 
            "title": "花生壳内网穿透", 
            "version": "3.0.6"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:38", 
            "description": "分布式的虚拟以太网", 
            "home_url": "Module_zerotier.asp", 
            "md5": "5fc4452e197361d84828e29710f2e885", 
            "name": "zerotier", 
            "tar_url": "zerotier/zerotier.tar.gz", 
            "title": "zerotier", 
            "version": "1.6"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:38", 
            "description": "解锁网易云灰色歌曲", 
            "home_url": "Module_unblockmusic.asp", 
            "md5": "3d9778e3b26588bbafdbd2325b31da79", 
            "name": "unblockmusic", 
            "tar_url": "unblockmusic/unblockmusic.tar.gz", 
            "title": "解锁网易云灰色歌曲", 
            "version": "1.2.1"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:39", 
            "description": "Cloudflare解析自动更新IP", 
            "home_url": "Module_cfddns.asp", 
            "md5": "239e81e2afd4c45f4764912225bacff6", 
            "name": "cfddns", 
            "tar_url": "cfddns/cfddns.tar.gz", 
            "title": "Cloudflare DDNS", 
            "version": "1.9"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:39", 
            "description": "灵缇游戏加速插件", 
            "home_url": "Module_lingti.asp", 
            "md5": "ff34bffba3e2ebc36a5a883df9c31cf7", 
            "name": "lingti", 
            "tar_url": "lingti/lingti.tar.gz", 
            "title": "灵缇游戏加速插件", 
            "version": "1.0.3"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2025-03-23_14:29:52", 
            "description": "lucky", 
            "home_url": "Module_lucky.asp", 
            "md5": "a530600aa3d3c3f068c69930889b0ac8", 
            "name": "lucky", 
            "tar_url": "lucky/lucky.tar.gz", 
            "title": "lucky", 
            "version": "1.4.3"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:39", 
            "description": "kms", 
            "home_url": "Module_kms.asp", 
            "md5": "dc12153ad245daefde4e34e8f8d638ed", 
            "name": "kms", 
            "tar_url": "kms/kms.tar.gz", 
            "title": "系统工具", 
            "version": "2.0"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:40", 
            "description": "解决重启Bug", 
            "home_url": "Module_reboothelper.asp", 
            "md5": "9be96b12dc2f26787323fcb15f9568f1", 
            "name": "reboothelper", 
            "tar_url": "reboothelper/reboothelper.tar.gz", 
            "title": "重启助手", 
            "version": "0.5"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2025-09-04_08:16:21", 
            "description": "支持Alidns(阿里云) Dnspod(腾讯云) Cloudflare 华为云 Callback", 
            "home_url": "Module_ddns.asp", 
            "md5": "3b94d07973bf6b04272c3d08e24a62db", 
            "name": "ddns", 
            "tar_url": "ddns/ddns.tar.gz", 
            "title": "多ddns合一", 
            "version": "0.4"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:41", 
            "description": "自己的私有云", 
            "home_url": "Module_verysync.asp", 
            "md5": "2f2e482ca57a14a9ea2197207e697845", 
            "name": "verysync", 
            "tar_url": "verysync/verysync.tar.gz", 
            "title": "微力同步", 
            "version": "1.1.1"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:41", 
            "description": "自动部署SSL证书", 
            "home_url": "Module_acme.asp", 
            "md5": "ca3391aa35b9d9020c8fb928fc49440d", 
            "name": "acme", 
            "tar_url": "acme/acme.tar.gz", 
            "title": "Let's Encrypt", 
            "version": "3.5"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2025-09-05_14:30:20", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frpc.asp", 
            "md5": "252332d6bb172e11679267a208807e87", 
            "name": "frpc", 
            "tar_url": "frpc/frpc.tar.gz", 
            "title": "frpc穿透", 
            "version": "2.6"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:42", 
            "description": "aliddns", 
            "home_url": "Module_aliddns.asp", 
            "md5": "1a1d98bebbbcc9fdd50a74d5094c6d91", 
            "name": "aliddns", 
            "tar_url": "aliddns/aliddns.tar.gz", 
            "title": "阿里DDNS", 
            "version": "2.6"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:43", 
            "description": "广告屏蔽大师 Plus 可以全面过滤各种横幅、弹窗、视频广告，同时阻止跟踪、隐私窃取及各种恶意网站", 
            "home_url": "Module_adbyby.asp", 
            "md5": "e8cc875254f9728baca68de4c7d1ffd6", 
            "name": "adbyby", 
            "tar_url": "adbyby/adbyby.tar.gz", 
            "title": "广告屏蔽大师 Plus", 
            "version": "1.4"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:43", 
            "description": "pppoe单线多拨，带宽提升神器！", 
            "home_url": "Module_mdial.asp", 
            "md5": "5a9f2af3db6adbd2303b23a339970352", 
            "name": "mdial", 
            "tar_url": "mdial/mdial.tar.gz", 
            "title": "单线多拨", 
            "version": "1.7"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:44", 
            "description": "linux下载利器", 
            "home_url": "Module_aria2.asp", 
            "md5": "0ae22ad5d6ae7fb01b9a06f2fa601432", 
            "name": "aria2", 
            "tar_url": "aria2/aria2.tar.gz", 
            "title": "Aria2", 
            "version": "3.2"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-12-04_18:20:21", 
            "description": "Cloudflare Tunnel 客户端(以前称为 Argo Tunnel)", 
            "home_url": "Module_cloudflared.asp", 
            "md5": "c9ad90dd626a4f38aa70f58134709ed7", 
            "name": "cloudflared", 
            "tar_url": "cloudflared/cloudflared.tar.gz", 
            "title": "cloudflared", 
            "version": "1.2"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:47", 
            "description": "这是一只自动帮你签到的dog", 
            "home_url": "Module_qiandao.asp", 
            "md5": "c6b885ce6e694e50695a40177c32929a", 
            "name": "qiandao", 
            "tar_url": "qiandao/qiandao.tar.gz", 
            "title": "签到dog", 
            "version": "1.8"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2025-09-04_12:06:49", 
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav。", 
            "home_url": "Module_openlist.asp", 
            "md5": "26f24282ba44aa87ef6ec70118f17f28", 
            "name": "openlist", 
            "tar_url": "openlist/openlist.tar.gz", 
            "title": "OpenList文件列表", 
            "version": "1.0"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:47", 
            "description": "光猫助手: 快速设置，通过路由直接访问猫后台", 
            "home_url": "Module_lookcat.asp", 
            "md5": "8c690943ba16927460e2c00c0d88cf1f", 
            "name": "lookcat", 
            "tar_url": "lookcat/lookcat.tar.gz", 
            "title": "光猫助手", 
            "version": "1.2"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2025-09-04_22:51:58", 
            "description": "超强的SSH网页客户端~", 
            "home_url": "Module_shellinabox.asp", 
            "md5": "5899b837540203857606bb024f98bb36", 
            "name": "shellinabox", 
            "tar_url": "shellinabox/shellinabox.tar.gz", 
            "title": "shellinabox", 
            "version": "2.5"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:48", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_serverchan.asp", 
            "md5": "c05442c6fc5e7d85924ebc61ebae4190", 
            "name": "serverchan", 
            "tar_url": "serverchan/serverchan.tar.gz", 
            "title": "ServerChan微信推送", 
            "version": "2.7"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:48", 
            "description": "使用Dnspod的ddns服务", 
            "home_url": "Module_ddnspod.asp", 
            "md5": "6e0dbe74d331b4bd1f64e9f6c114f0c6", 
            "name": "ddnspod", 
            "tar_url": "ddnspod/ddnspod.tar.gz", 
            "title": "DDnspod", 
            "version": "2.0"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:54", 
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav，后端基于gin，前端使用react。", 
            "home_url": "Module_alist.asp", 
            "md5": "716bec5a57647c13e7cab2219bac983f", 
            "name": "alist", 
            "tar_url": "alist/alist.tar.gz", 
            "title": "Alist文件列表", 
            "version": "1.9.2"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:58", 
            "description": "百度盘", 
            "home_url": "Module_baidupcs.asp", 
            "md5": "3aee0c65dfba57a76bdd0edf56442ec9", 
            "name": "baidupcs", 
            "tar_url": "baidupcs/baidupcs.tar.gz", 
            "title": "百度盘", 
            "version": "1.9"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:59", 
            "description": "DDNSTO远程控制", 
            "home_url": "Module_ddnsto.asp", 
            "md5": "67d7612dbe6cc0d2eb5dea16819fb66b", 
            "name": "ddnsto", 
            "tar_url": "ddnsto/ddnsto.tar.gz", 
            "title": "DDNSTO远程控制", 
            "version": "3.0.3"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-11-09_12:35:59", 
            "description": "腾讯云ddns", 
            "home_url": "Module_tenddns.asp", 
            "md5": "261951f04428813b476c07b11ee64f5c", 
            "name": "tenddns", 
            "tar_url": "tenddns/tenddns.tar.gz", 
            "title": "腾讯云ddns", 
            "version": "0.0.4"
        }
    ], 
    "home_url": "https://raw.githubusercontent.com/SWRT-dev/softcenter/master", 
    "md5": "6698713c3ce9617e1c925d98d3189e55", 
    "tar_url": "softcenter/softcenter.tar.gz", 
    "version": "1.5.6"
}