{
    "apps": [
        {
            "arch": "mipsle",
            "build_date": "2026-05-28_09:20:14",
            "description": "内网穿透利器，谁用谁知道。",
            "home_url": "Module_frps.asp",
            "md5": "6aa0f7f8f88164438ed142725e1f1867",
            "name": "frps",
            "rc_support": "",
            "tar_url": "frps/frps.tar.gz",
            "title": "frps穿透服务器",
            "version": "2.3"
        },
        {
            "arch": "mipsle",
            "build_date": "2024-11-09_12:35:20",
            "description": "简便高效的异地组网、内网穿透工具",
            "home_url": "Module_vnt.asp",
            "md5": "58d0b93d1a6568ca80ca73a9fce565f5",
            "name": "vnt",
            "tar_url": "vnt/vnt.tar.gz",
            "title": "vnt",
            "version": "1.2"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-28_14:07:45",
            "description": "node.js",
            "home_url": "Module_node.asp",
            "md5": "e91968b904f1539cf8b9490b9eeb7a5c",
            "name": "node",
            "rc_support": "",
            "tar_url": "node/node.tar.gz",
            "title": "node.js",
            "version": "0.0.7"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-01-10_15:26:24",
            "description": "tailscale",
            "home_url": "Module_tailscale.asp",
            "md5": "1b11ef0102f488aa76d8cb48e249f1d4",
            "name": "tailscale",
            "tar_url": "tailscale/tailscale.tar.gz",
            "title": "tailscale",
            "version": "0.1.2"
        },
        {
            "arch": "mipsle",
            "build_date": "2025-09-04_22:50:38",
            "description": "Socat 端口转发",
            "home_url": "Module_socat.asp",
            "md5": "2f47fd58cfb54dca49b65b53a9e935e1",
            "name": "socat",
            "tar_url": "socat/socat.tar.gz",
            "title": "Socat端口转发",
            "version": "1.2"
        },
        {
            "arch": "mipsle",
            "build_date": "2025-12-31_08:55:20",
            "description": "VPN全家桶, ver 4.44 build 9807",
            "home_url": "",
            "md5": "872abd4561faa45000e189997f0c1ce3",
            "name": "softether",
            "tar_url": "softether/softether.tar.gz",
            "title": "SoftEther_VPN_Server",
            "version": "2.7"
        },
        {
            "arch": "mipsle",
            "build_date": "2024-11-09_12:35:32",
            "description": "局域网网速测试工具",
            "home_url": "Module_speedtest.asp",
            "md5": "eb30a643c9c1f53b5c756ae914f56d22",
            "name": "speedtest",
            "tar_url": "speedtest/speedtest.tar.gz",
            "title": "局域网测速",
            "version": "0.0.4"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-28_08:07:48",
            "description": "FileBrowser：您的可视化路由文件管理系统",
            "home_url": "Module_filebrowser.asp",
            "md5": "b2a6ee45218b15e1d0123bff27faab67",
            "name": "filebrowser",
            "rc_support": "",
            "tar_url": "filebrowser/filebrowser.tar.gz",
            "title": "filebrowser",
            "version": "1.0.9"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-28_10:23:29",
            "description": "去广告，没烦恼",
            "home_url": "Module_koolproxy.asp",
            "md5": "1ba7dc044400ed2b3f26b28ad2871098",
            "name": "koolproxy",
            "rc_support": "",
            "tar_url": "koolproxy/koolproxy.tar.gz",
            "title": "koolproxy",
            "version": "3.8.5.7"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-26_15:22:23",
            "description": "阿里云盘 WebDAV 服务器",
            "home_url": "Module_aliyundrivewebdav.asp",
            "md5": "e22b55ddda44b8d86fb4f6c703ae9e78",
            "name": "aliyundrivewebdav",
            "rc_support": "",
            "tar_url": "aliyundrivewebdav/aliyundrivewebdav.tar.gz",
            "title": "阿里云盘WebDAV",
            "version": "1.8.3"
        },
        {
            "arch": "mipsle",
            "build_date": "2024-11-09_12:35:36",
            "description": "老板，来一斤虚拟内存~",
            "home_url": "Module_swap.asp",
            "md5": "e0e9d8147bb47d6421d6a82221286444",
            "name": "swap",
            "tar_url": "swap/swap.tar.gz",
            "title": "虚拟内存",
            "version": "2.6"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-28_14:40:12",
            "description": "花生壳内网穿透",
            "home_url": "Module_phddns.asp",
            "md5": "a9e0c824dc10cec12e68f63bcdfb9275",
            "name": "phddns",
            "rc_support": "",
            "tar_url": "phddns/phddns.tar.gz",
            "title": "花生壳内网穿透",
            "version": "3.0.7"
        },
        {
            "arch": "mipsle",
            "build_date": "2024-11-09_12:35:38",
            "description": "分布式的虚拟以太网",
            "home_url": "Module_zerotier.asp",
            "md5": "5fc4452e197361d84828e29710f2e885",
            "name": "zerotier",
            "tar_url": "zerotier/zerotier.tar.gz",
            "title": "zerotier",
            "version": "1.6"
        },
        {
            "arch": "mipsle",
            "build_date": "2024-11-09_12:35:38",
            "description": "解锁网易云灰色歌曲",
            "home_url": "Module_unblockmusic.asp",
            "md5": "3d9778e3b26588bbafdbd2325b31da79",
            "name": "unblockmusic",
            "tar_url": "unblockmusic/unblockmusic.tar.gz",
            "title": "解锁网易云灰色歌曲",
            "version": "1.2.1"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-26_21:19:00",
            "description": "Cloudflare解析自动更新IP",
            "home_url": "Module_cfddns.asp",
            "md5": "bfc4007266c1290215f30e98ab735113",
            "name": "cfddns",
            "rc_support": "",
            "tar_url": "cfddns/cfddns.tar.gz",
            "title": "Cloudflare DDNS",
            "version": "2.0"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-28_12:11:20",
            "description": "灵缇游戏加速插件",
            "home_url": "Module_lingti.asp",
            "md5": "249ce28946c91d6d04bce234bc0a43c4",
            "name": "lingti",
            "rc_support": "",
            "tar_url": "lingti/lingti.tar.gz",
            "title": "灵缇游戏加速插件",
            "version": "1.0.4"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-28_12:53:01",
            "description": "lucky",
            "home_url": "Module_lucky.asp",
            "md5": "a7fc6741b78934b344b429fa6bb9d623",
            "name": "lucky",
            "rc_support": "",
            "tar_url": "lucky/lucky.tar.gz",
            "title": "lucky",
            "version": "1.4.4"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-28_09:27:32",
            "description": "kms",
            "home_url": "Module_kms.asp",
            "md5": "b47a4097d5192c5d0bc426849280c49c",
            "name": "kms",
            "rc_support": "",
            "tar_url": "kms/kms.tar.gz",
            "title": "系统工具",
            "version": "2.1"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-28_15:24:06",
            "description": "解决重启Bug",
            "home_url": "Module_reboothelper.asp",
            "md5": "7df3cebdcaeba33952d009f97f293eba",
            "name": "reboothelper",
            "rc_support": "",
            "tar_url": "reboothelper/reboothelper.tar.gz",
            "title": "重启助手",
            "version": "0.6"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-26_23:02:27",
            "description": "支持Alidns(阿里云) Dnspod(腾讯云) Cloudflare 华为云 Callback",
            "home_url": "Module_ddns.asp",
            "md5": "729b1de4bfe6ffa3bb1f0292b8009b7a",
            "name": "ddns",
            "rc_support": "",
            "tar_url": "ddns/ddns.tar.gz",
            "title": "多ddns合一",
            "version": "0.5"
        },
        {
            "arch": "mipsle",
            "build_date": "2024-11-09_12:35:41",
            "description": "自己的私有云",
            "home_url": "Module_verysync.asp",
            "md5": "2f2e482ca57a14a9ea2197207e697845",
            "name": "verysync",
            "tar_url": "verysync/verysync.tar.gz",
            "title": "微力同步",
            "version": "1.1.1"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-26_10:23:56",
            "description": "自动部署SSL证书",
            "home_url": "Module_acme.asp",
            "md5": "6ff958c93c88c79890267d1334b1d8e9",
            "name": "acme",
            "rc_support": "",
            "tar_url": "acme/acme.tar.gz",
            "title": "Let's Encrypt",
            "version": "3.6"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-28_09:07:43",
            "description": "内网穿透利器，谁用谁知道。",
            "home_url": "Module_frpc.asp",
            "md5": "b03dec383c52806c4bca57bf93e3eb9a",
            "name": "frpc",
            "rc_support": "",
            "tar_url": "frpc/frpc.tar.gz",
            "title": "frpc穿透",
            "version": "2.7"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-26_13:02:18",
            "description": "aliddns",
            "home_url": "Module_aliddns.asp",
            "md5": "260121f1658197d3fd02e5fdd87ae587",
            "name": "aliddns",
            "rc_support": "",
            "tar_url": "aliddns/aliddns.tar.gz",
            "title": "阿里DDNS",
            "version": "2.7"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-26_12:30:10",
            "description": "广告屏蔽大师 Plus 可以全面过滤各种横幅、弹窗、视频广告，同时阻止跟踪、隐私窃取及各种恶意网站",
            "home_url": "Module_adbyby.asp",
            "md5": "d1f48e9ba1062845eef796dbfcae6888",
            "name": "adbyby",
            "rc_support": "",
            "tar_url": "adbyby/adbyby.tar.gz",
            "title": "广告屏蔽大师 Plus",
            "version": "1.5"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-28_13:57:00",
            "description": "pppoe单线多拨，带宽提升神器！",
            "home_url": "Module_mdial.asp",
            "md5": "a38e46965b39459292c8f0146f3f3ad1",
            "name": "mdial",
            "rc_support": "",
            "tar_url": "mdial/mdial.tar.gz",
            "title": "单线多拨",
            "version": "1.8"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-26_17:11:01",
            "description": "linux下载利器",
            "home_url": "Module_aria2.asp",
            "md5": "03e1f81d0160f300479f65ad2c88ffb0",
            "name": "aria2",
            "rc_support": "",
            "tar_url": "aria2/aria2.tar.gz",
            "title": "Aria2",
            "version": "3.3"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-26_21:48:46",
            "description": "Cloudflare Tunnel 客户端(以前称为 Argo Tunnel)",
            "home_url": "Module_cloudflared.asp",
            "md5": "ce923dc7e448e45ddb4cccef5360d997",
            "name": "cloudflared",
            "rc_support": "",
            "tar_url": "cloudflared/cloudflared.tar.gz",
            "title": "cloudflared",
            "version": "1.3"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-28_14:24:58",
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav。",
            "home_url": "Module_openlist.asp",
            "md5": "0ae63727d83de2dc431d1939997ec1bb",
            "name": "openlist",
            "rc_support": "",
            "tar_url": "openlist/openlist.tar.gz",
            "title": "OpenList文件列表",
            "version": "1.2"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-28_12:35:12",
            "description": "光猫助手: 快速设置，通过路由直接访问猫后台",
            "home_url": "Module_lookcat.asp",
            "md5": "0065ab2e9858b0e1fe2db4051e38a1ed",
            "name": "lookcat",
            "rc_support": "",
            "tar_url": "lookcat/lookcat.tar.gz",
            "title": "光猫助手",
            "version": "1.3"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-28_17:09:31",
            "description": "超强的SSH网页客户端~",
            "home_url": "Module_shellinabox.asp",
            "md5": "46506610b4f943d06ecaaf9b1bb122b8",
            "name": "shellinabox",
            "rc_support": "",
            "tar_url": "shellinabox/shellinabox.tar.gz",
            "title": "shellinabox",
            "version": "2.6"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-28_16:25:06",
            "description": "从路由器推送状态及通知的工具",
            "home_url": "Module_serverchan.asp",
            "md5": "bd9c094bd22a9d60a813951a8d4d46d0",
            "name": "serverchan",
            "rc_support": "",
            "tar_url": "serverchan/serverchan.tar.gz",
            "title": "ServerChan微信推送",
            "version": "2.8"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-28_07:23:16",
            "description": "使用Dnspod的ddns服务",
            "home_url": "Module_ddnspod.asp",
            "md5": "f8ae298f74c36ae8fc8ae4ccea1bb1f2",
            "name": "ddnspod",
            "rc_support": "",
            "tar_url": "ddnspod/ddnspod.tar.gz",
            "title": "DDnspod",
            "version": "2.1"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-26_13:24:28",
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav，后端基于gin，前端使用react。",
            "home_url": "Module_alist.asp",
            "md5": "be36e578ca719001a88eb17354db1611",
            "name": "alist",
            "rc_support": "",
            "tar_url": "alist/alist.tar.gz",
            "title": "Alist文件列表",
            "version": "1.9.3"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-26_18:42:43",
            "description": "百度盘",
            "home_url": "Module_baidupcs.asp",
            "md5": "71f8ad57e43413cfc9594a7ba0ccd15c",
            "name": "baidupcs",
            "rc_support": "",
            "tar_url": "baidupcs/baidupcs.tar.gz",
            "title": "百度盘",
            "version": "2.0"
        },
        {
            "arch": "mipsle",
            "build_date": "2026-05-28_07:34:15",
            "description": "DDNSTO远程控制",
            "home_url": "Module_ddnsto.asp",
            "md5": "e07c207360919135ef746cc152f45442",
            "name": "ddnsto",
            "rc_support": "",
            "tar_url": "ddnsto/ddnsto.tar.gz",
            "title": "DDNSTO远程控制",
            "version": "3.0.4"
        },
        {
            "arch": "mipsle",
            "build_date": "2024-11-09_12:35:59",
            "description": "腾讯云ddns",
            "home_url": "Module_tenddns.asp",
            "md5": "261951f04428813b476c07b11ee64f5c",
            "name": "tenddns",
            "tar_url": "tenddns/tenddns.tar.gz",
            "title": "腾讯云ddns",
            "version": "0.0.4"
        }
    ],
    "home_url": "https://raw.githubusercontent.com/SWRT-dev/softcenter/master",
    "md5": "aeb3759c123171b22ecbea8fe8ae5e7f",
    "tar_url": "softcenter/softcenter.tar.gz",
    "version": "1.5.8"
}