{
    "apps": [
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:11:49", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frps.asp", 
            "md5": "1792ca434c33631a7289bad89b2876b2", 
            "name": "frps", 
            "tar_url": "mipsle/frps/frps.tar.gz", 
            "title": "frps穿透服务器", 
            "version": "2.1"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:11:49", 
            "description": "简便高效的异地组网、内网穿透工具", 
            "home_url": "Module_vnt.asp", 
            "md5": "2c6ec5089d4a59c83fd4604e2cdb022b", 
            "name": "vnt", 
            "tar_url": "mipsle/vnt/vnt.tar.gz", 
            "title": "vnt", 
            "version": "1.2"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:11:50", 
            "description": "node.js", 
            "home_url": "Module_node.asp", 
            "md5": "dfebad3d06cfa8897ba0797f79f05cd6", 
            "name": "node", 
            "tar_url": "mipsle/node/node.tar.gz", 
            "title": "node.js", 
            "version": "0.0.6"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:11:55", 
            "description": "tailscale", 
            "home_url": "Module_tailscale.asp", 
            "md5": "8fa8ebaee082d3c8f5787af0d1f8e70f", 
            "name": "tailscale", 
            "tar_url": "mipsle/tailscale/tailscale.tar.gz", 
            "title": "tailscale", 
            "version": "0.0.8"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:11:55", 
            "description": "Socat 端口转发", 
            "home_url": "Module_socat.asp", 
            "md5": "1f3faed92b313f8b2bd5781962e78676", 
            "name": "socat", 
            "tar_url": "mipsle/socat/socat.tar.gz", 
            "title": "Socat端口转发", 
            "version": "1.1"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:11:56", 
            "description": "VPN全家桶, ver 4.30 build 9700", 
            "home_url": "", 
            "md5": "8efa7f38ae9bc2955166ffacea787b02", 
            "name": "softether", 
            "tar_url": "mipsle/softether/softether.tar.gz", 
            "title": "SoftEther_VPN_Server", 
            "version": "2.4"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:11:57", 
            "description": "局域网网速测试工具", 
            "home_url": "Module_speedtest.asp", 
            "md5": "21cb189961b65dccb3cfbc12bc8679f8", 
            "name": "speedtest", 
            "tar_url": "mipsle/speedtest/speedtest.tar.gz", 
            "title": "局域网测速", 
            "version": "0.0.4"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:11:59", 
            "description": "FileBrowser：您的可视化路由文件管理系统", 
            "home_url": "Module_filebrowser.asp", 
            "md5": "f855b646fa37b759c6676e8857722db6", 
            "name": "filebrowser", 
            "tar_url": "mipsle/filebrowser/filebrowser.tar.gz", 
            "title": "filebrowser", 
            "version": "1.0.7"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:11:59", 
            "description": "去广告，没烦恼", 
            "home_url": "Module_koolproxy.asp", 
            "md5": "8622dad927fd817c7c05eb37e9da03a4", 
            "name": "koolproxy", 
            "tar_url": "mipsle/koolproxy/koolproxy.tar.gz", 
            "title": "koolproxy", 
            "version": "3.8.5.6"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:00", 
            "description": "阿里云盘 WebDAV 服务器", 
            "home_url": "Module_aliyundrivewebdav.asp", 
            "md5": "3ec4e9cbc1f9464b30103ccaed5f699f", 
            "name": "aliyundrivewebdav", 
            "tar_url": "mipsle/aliyundrivewebdav/aliyundrivewebdav.tar.gz", 
            "title": "阿里云盘WebDAV", 
            "version": "1.8.2"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:00", 
            "description": "老板，来一斤虚拟内存~", 
            "home_url": "Module_swap.asp", 
            "md5": "c3a1462d390de990d812954c70c776f4", 
            "name": "swap", 
            "tar_url": "mipsle/swap/swap.tar.gz", 
            "title": "虚拟内存", 
            "version": "2.6"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:01", 
            "description": "花生壳内网穿透", 
            "home_url": "Module_phddns.asp", 
            "md5": "ebf898c7deb2c37efb766888ad3eaeb5", 
            "name": "phddns", 
            "tar_url": "mipsle/phddns/phddns.tar.gz", 
            "title": "花生壳内网穿透", 
            "version": "3.0.6"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:01", 
            "description": "分布式的虚拟以太网", 
            "home_url": "Module_zerotier.asp", 
            "md5": "be810238e6cbf17e1633544e45bee242", 
            "name": "zerotier", 
            "tar_url": "mipsle/zerotier/zerotier.tar.gz", 
            "title": "zerotier", 
            "version": "1.6"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:02", 
            "description": "解锁网易云灰色歌曲", 
            "home_url": "Module_unblockmusic.asp", 
            "md5": "286d2ea5de92b94c32cd8f98a0ad952d", 
            "name": "unblockmusic", 
            "tar_url": "mipsle/unblockmusic/unblockmusic.tar.gz", 
            "title": "解锁网易云灰色歌曲", 
            "version": "1.2.1"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:02", 
            "description": "Cloudflare解析自动更新IP", 
            "home_url": "Module_cfddns.asp", 
            "md5": "2561eaf2be02c6310496cf2f01a37f5c", 
            "name": "cfddns", 
            "tar_url": "mipsle/cfddns/cfddns.tar.gz", 
            "title": "Cloudflare DDNS", 
            "version": "1.9"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:02", 
            "description": "灵缇游戏加速插件", 
            "home_url": "Module_lingti.asp", 
            "md5": "477b157633e6f8764566ecc33466077a", 
            "name": "lingti", 
            "tar_url": "mipsle/lingti/lingti.tar.gz", 
            "title": "灵缇游戏加速插件", 
            "version": "1.0.3"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:03", 
            "description": "kms", 
            "home_url": "Module_kms.asp", 
            "md5": "76357ce2b8f3dc30feca0e8f129f714b", 
            "name": "kms", 
            "tar_url": "mipsle/kms/kms.tar.gz", 
            "title": "系统工具", 
            "version": "2.0"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:03", 
            "description": "解决重启Bug", 
            "home_url": "Module_reboothelper.asp", 
            "md5": "e815580141b1028700b70166cf57c6fd", 
            "name": "reboothelper", 
            "tar_url": "mipsle/reboothelper/reboothelper.tar.gz", 
            "title": "重启助手", 
            "version": "0.5"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:03", 
            "description": "支持Alidns(阿里云) Dnspod(腾讯云) Cloudflare 华为云 Callback", 
            "home_url": "Module_ddns.asp", 
            "md5": "c59692b6f4713f721f47d8bbad80ddf0", 
            "name": "ddns", 
            "tar_url": "mipsle/ddns/ddns.tar.gz", 
            "title": "多ddns合一", 
            "version": "0.3"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:03", 
            "description": "自己的私有云", 
            "home_url": "Module_verysync.asp", 
            "md5": "72a678631a0f6e0acd58d1ef85ef3da4", 
            "name": "verysync", 
            "tar_url": "mipsle/verysync/verysync.tar.gz", 
            "title": "微力同步", 
            "version": "1.1.1"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:03", 
            "description": "自动部署SSL证书", 
            "home_url": "Module_acme.asp", 
            "md5": "49ddb261736fa86b01da729dbebc8956", 
            "name": "acme", 
            "tar_url": "mipsle/acme/acme.tar.gz", 
            "title": "Let's Encrypt", 
            "version": "3.5"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:04", 
            "description": "内网穿透利器，谁用谁知道。", 
            "home_url": "Module_frpc.asp", 
            "md5": "288b818d2cc627a5557fbfdce6fd79cf", 
            "name": "frpc", 
            "tar_url": "mipsle/frpc/frpc.tar.gz", 
            "title": "frpc穿透", 
            "version": "2.5"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:04", 
            "description": "aliddns", 
            "home_url": "Module_aliddns.asp", 
            "md5": "d50941e8aaf960d50f967c495e6deb42", 
            "name": "aliddns", 
            "tar_url": "mipsle/aliddns/aliddns.tar.gz", 
            "title": "阿里DDNS", 
            "version": "2.6"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:05", 
            "description": "广告屏蔽大师 Plus 可以全面过滤各种横幅、弹窗、视频广告，同时阻止跟踪、隐私窃取及各种恶意网站", 
            "home_url": "Module_adbyby.asp", 
            "md5": "abc04b0670a5cde2c5e59200a38f14da", 
            "name": "adbyby", 
            "tar_url": "mipsle/adbyby/adbyby.tar.gz", 
            "title": "广告屏蔽大师 Plus", 
            "version": "1.4"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:05", 
            "description": "pppoe单线多拨，带宽提升神器！", 
            "home_url": "Module_mdial.asp", 
            "md5": "647e122d5b5763cd4f1fc88253c94b3b", 
            "name": "mdial", 
            "tar_url": "mipsle/mdial/mdial.tar.gz", 
            "title": "单线多拨", 
            "version": "1.7"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:06", 
            "description": "linux下载利器", 
            "home_url": "Module_aria2.asp", 
            "md5": "773a706f6051fd9b18c67f49360ead08", 
            "name": "aria2", 
            "tar_url": "mipsle/aria2/aria2.tar.gz", 
            "title": "Aria2", 
            "version": "3.2"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:07", 
            "description": "Cloudflare Tunnel 客户端(以前称为 Argo Tunnel)", 
            "home_url": "Module_cloudflared.asp", 
            "md5": "d2bd4beb3f5a9c7066157a5e839f4df9", 
            "name": "cloudflared", 
            "tar_url": "mipsle/cloudflared/cloudflared.tar.gz", 
            "title": "cloudflared", 
            "version": "1.1"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:08", 
            "description": "这是一只自动帮你签到的dog", 
            "home_url": "Module_qiandao.asp", 
            "md5": "d9cc240752629bc4b53a8d7e5000ca8c", 
            "name": "qiandao", 
            "tar_url": "mipsle/qiandao/qiandao.tar.gz", 
            "title": "签到dog", 
            "version": "1.8"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:08", 
            "description": "光猫助手: 快速设置，通过路由直接访问猫后台", 
            "home_url": "Module_lookcat.asp", 
            "md5": "7987fead89eac37187e1be4423a847e1", 
            "name": "lookcat", 
            "tar_url": "mipsle/lookcat/lookcat.tar.gz", 
            "title": "光猫助手", 
            "version": "1.2"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:08", 
            "description": "超强的SSH网页客户端~", 
            "home_url": "Module_shellinabox.asp", 
            "md5": "87d105561cf0ab8c57788ff3410be3c9", 
            "name": "shellinabox", 
            "tar_url": "mipsle/shellinabox/shellinabox.tar.gz", 
            "title": "shellinabox", 
            "version": "2.5"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:08", 
            "description": "从路由器推送状态及通知的工具", 
            "home_url": "Module_serverchan.asp", 
            "md5": "0d47fd24a34bdb672919d38d2054261e", 
            "name": "serverchan", 
            "tar_url": "mipsle/serverchan/serverchan.tar.gz", 
            "title": "ServerChan微信推送", 
            "version": "2.7"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:09", 
            "description": "使用Dnspod的ddns服务", 
            "home_url": "Module_ddnspod.asp", 
            "md5": "56ac462bf5242f2ea46c3ca7f9a3494d", 
            "name": "ddnspod", 
            "tar_url": "mipsle/ddnspod/ddnspod.tar.gz", 
            "title": "DDnspod", 
            "version": "2.0"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:13", 
            "description": "一款支持多种存储的目录文件列表程序，支持 web 浏览与 webdav，后端基于gin，前端使用react。", 
            "home_url": "Module_alist.asp", 
            "md5": "37aa6176d5a4f71b8d626f3b4cd73725", 
            "name": "alist", 
            "tar_url": "mipsle/alist/alist.tar.gz", 
            "title": "Alist文件列表", 
            "version": "1.9.2"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:16", 
            "description": "百度盘", 
            "home_url": "Module_baidupcs.asp", 
            "md5": "3a875834638980945a6d1ef33c4634a1", 
            "name": "baidupcs", 
            "tar_url": "mipsle/baidupcs/baidupcs.tar.gz", 
            "title": "百度盘", 
            "version": "1.9"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:16", 
            "description": "DDNSTO远程控制", 
            "home_url": "Module_ddnsto.asp", 
            "md5": "9f0777b48e8bbac85ab16588ea3cfae0", 
            "name": "ddnsto", 
            "tar_url": "mipsle/ddnsto/ddnsto.tar.gz", 
            "title": "DDNSTO远程控制", 
            "version": "3.0.3"
        }, 
        {
            "arch": "mipsle", 
            "build_date": "2024-10-31_14:12:16", 
            "description": "腾讯云ddns", 
            "home_url": "Module_tenddns.asp", 
            "md5": "9c0d87c63fdb6211f18f6d71049266e5", 
            "name": "tenddns", 
            "tar_url": "mipsle/tenddns/tenddns.tar.gz", 
            "title": "腾讯云ddns", 
            "version": "0.0.4"
        }
    ], 
    "home_url": "https://raw.githubusercontent.com/SWRT-dev/softcenter/master", 
    "md5": "8e063301c57c86d9ca66ecc1229e80da", 
    "tar_url": "mipsle/softcenter/softcenter.tar.gz", 
    "version": "1.5.4"
}